//
//  Product.swift
//  FitnessPad
//
//  Created by Марк Кулик on 29.01.2025.
//

import Foundation

struct Product: Identifiable {
    let id = UUID()
    let name: String
    let category: String
    let proteins: Double
    let fats: Double
    let carbohydrates: Double
    let calories: Double
}

let productsByCategory: [String: [Product]] = [
    "Хлебобулочные изделия": [
        Product(name: "Хлеб пшеничный из муки высшего сорта", category: "Хлебобулочные изделия", proteins: 7.5, fats: 0.8, carbohydrates: 49.2, calories: 235),
        Product(name: "Хлеб пшеничный из муки 1 сорта", category: "Хлебобулочные изделия", proteins: 7.6, fats: 0.9, carbohydrates: 49.7, calories: 226),
        Product(name: "Хлеб из ржано-пшеничной муки", category: "Хлебобулочные изделия", proteins: 6.8, fats: 1.2, carbohydrates: 46.4, calories: 215),
        Product(name: "Хлеб ржаной", category: "Хлебобулочные изделия", proteins: 4.7, fats: 0.7, carbohydrates: 49.8, calories: 214),
        Product(name: "Хлеб 'Бородинский'", category: "Хлебобулочные изделия", proteins: 6.9, fats: 1.3, carbohydrates: 40.9, calories: 208),
        Product(name: "Хлеб зерновой (мука пшеничная в/с, зерно дробленое)", category: "Хлебобулочные изделия", proteins: 8.6, fats: 1.4, carbohydrates: 45.1, calories: 228),
        Product(name: "Хлеб цельнозерновой из смеси злаков", category: "Хлебобулочные изделия", proteins: 13.3, fats: 4.2, carbohydrates: 43.3, calories: 265),
        Product(name: "Хлебцы Dr.Körner 'Семь злаков'", category: "Хлебобулочные изделия", proteins: 10, fats: 2, carbohydrates: 57, calories: 290),
        Product(name: "Хлебцы Dr.Körner 'Бородинские'", category: "Хлебобулочные изделия", proteins: 11, fats: 3, carbohydrates: 52, calories: 280),
        Product(name: "Хлебцы Dr.Körner 'Гречневые' с витаминами", category: "Хлебобулочные изделия", proteins: 11.6, fats: 3, carbohydrates: 52.4, calories: 283),
        Product(name: "Хлебцы Dr.Körner 'Рисовые' с витаминами", category: "Хлебобулочные изделия", proteins: 6, fats: 1, carbohydrates: 69, calories: 310),
        Product(name: "Сдоба", category: "Хлебобулочные изделия", proteins: 7.4, fats: 2.2, carbohydrates: 52.9, calories: 269),
        Product(name: "Сухари из пшеничной муки", category: "Хлебобулочные изделия", proteins: 11.2, fats: 1.4, carbohydrates: 72.4, calories: 331)
    ],
    "Макароны, крупы": [
        Product(name: "Макаронные изделия из муки твердых сортов в/с", category: "Макароны, крупы", proteins: 11, fats: 1.3, carbohydrates: 70.5, calories: 338),
        Product(name: "Макаронные изделия из муки твердых сортов в/с, вареные", category: "Макароны, крупы", proteins: 3.6, fats: 0.4, carbohydrates: 20, calories: 98),
        Product(name: "Макаронные изделия в/с", category: "Макароны, крупы", proteins: 10.4, fats: 1.1, carbohydrates: 69.7, calories: 337),
        Product(name: "Макаронные изделия в/с, варенье", category: "Макароны, крупы", proteins: 3.5, fats: 0.4, carbohydrates: 23.2, calories: 112),
        Product(name: "Крупа гречневая ядрица", category: "Макароны, крупы", proteins: 12.6, fats: 3.3, carbohydrates: 57.1, calories: 308),
        Product(name: "Гречка вареная", category: "Макароны, крупы", proteins: 4.1, fats: 1, carbohydrates: 18.5, calories: 100),
        Product(name: "Гречневый продел", category: "Макароны, крупы", proteins: 9.5, fats: 2.3, carbohydrates: 60.4, calories: 300),
        Product(name: "Гречка зеленая ('Мистраль')", category: "Макароны, крупы", proteins: 13.4, fats: 3, carbohydrates: 68, calories: 328),
        Product(name: "Рис белый шлифованный", category: "Макароны, крупы", proteins: 7, fats: 1, carbohydrates: 74, calories: 333),
        Product(name: "Рис белый шлифованный вареный", category: "Макароны, крупы", proteins: 2.3, fats: 0.2, carbohydrates: 28.7, calories: 130),
        Product(name: "Рис длиннозерный нешлифованный", category: "Макароны, крупы", proteins: 7.5, fats: 2, carbohydrates: 73, calories: 340),
        Product(name: "Рис нешлифованный вареный", category: "Макароны, крупы", proteins: 2.5, fats: 0.9, carbohydrates: 23, calories: 112),
        Product(name: "Рис красный нешлифованный", category: "Макароны, крупы", proteins: 7.5, fats: 3, carbohydrates: 68, calories: 330),
        Product(name: "Рис дикий черный (цицания водная)", category: "Макароны, крупы", proteins: 14.7, fats: 1.1, carbohydrates: 68.7, calories: 357),
        Product(name: "Рис дикий черный вареный", category: "Макароны, крупы", proteins: 4, fats: 0.3, carbohydrates: 19.5, calories: 101),
        Product(name: "Пшено", category: "Макароны, крупы", proteins: 11.5, fats: 3.3, carbohydrates: 66.5, calories: 342),
        Product(name: "Пшено вареное", category: "Макароны, крупы", proteins: 3.5, fats: 1.1, carbohydrates: 23.6, calories: 119),
        Product(name: "Крупа овсяная", category: "Макароны, крупы", proteins: 12.3, fats: 6.1, carbohydrates: 59.5, calories: 342),
        Product(name: "Овсяные хлопья", category: "Макароны, крупы", proteins: 12.3, fats: 6.2, carbohydrates: 61.8, calories: 352),
        Product(name: "Каша из овсяных хлопьев на воде", category: "Макароны, крупы", proteins: 3, fats: 1.7, carbohydrates: 15, calories: 88),
        Product(name: "Каша из овсяных хлопьев на молоке", category: "Макароны, крупы", proteins: 3.2, fats: 4.1, carbohydrates: 14.2, calories: 102),
        Product(name: "Толокно овсяное", category: "Макароны, крупы", proteins: 12.5, fats: 6, carbohydrates: 64.9, calories: 363),
        Product(name: "Перловая крупа", category: "Макароны, крупы", proteins: 9.3, fats: 1.1, carbohydrates: 66.9, calories: 315),
        Product(name: "Перловая крупа вареная", category: "Макароны, крупы", proteins: 3.1, fats: 0.4, carbohydrates: 22.2, calories: 109),
        Product(name: "Ячневая крупа", category: "Макароны, крупы", proteins: 10, fats: 1.3, carbohydrates: 65.4, calories: 313),
        Product(name: "Ячневая крупа вареная", category: "Макароны, крупы", proteins: 2.3, fats: 0.3, carbohydrates: 15.7, calories: 76),
        Product(name: "Крупа пшеничная 'Полтавская'", category: "Макароны, крупы", proteins: 11.5, fats: 1.3, carbohydrates: 67.9, calories: 329),
        Product(name: "Крупа пшеничная 'Полтавская' вареная", category: "Макароны, крупы", proteins: 2.5, fats: 0.3, carbohydrates: 14.5, calories: 71),
        Product(name: "Кукуруза, зерно продовольственное", category: "Макароны, крупы", proteins: 10.3, fats: 4.9, carbohydrates: 60, calories: 325),
        Product(name: "Кукурузная крупа", category: "Макароны, крупы", proteins: 8.3, fats: 1.2, carbohydrates: 71, calories: 328),
        Product(name: "Манная крупа", category: "Макароны, крупы", proteins: 10.3, fats: 1, carbohydrates: 70.6, calories: 333),
        Product(name: "Манная каша на воде", category: "Макароны, крупы", proteins: 2.5, fats: 0.2, carbohydrates: 16.8, calories: 80),
        Product(name: "Манная каша на молоке", category: "Макароны, крупы", proteins: 3, fats: 3.2, carbohydrates: 15.3, calories: 98)
    ],

    "Бобовые": [
        Product(name: "Горох зерно", category: "Бобовые", proteins: 20.5, fats: 2, carbohydrates: 49.5, calories: 298),
        Product(name: "Горох целый шлифованный", category: "Бобовые", proteins: 22, fats: 2, carbohydrates: 57, calories: 330),
        Product(name: "Горох колотый", category: "Бобовые", proteins: 23, fats: 1.6, carbohydrates: 48.1, calories: 299),
        Product(name: "Горох вареный", category: "Бобовые", proteins: 8.3, fats: 0.4, carbohydrates: 21, calories: 118),
        Product(name: "Горошек зеленый свежий", category: "Бобовые", proteins: 5, fats: 0.2, carbohydrates: 8.3, calories: 55),
        Product(name: "Маш", category: "Бобовые", proteins: 23.9, fats: 1.2, carbohydrates: 62.6, calories: 347),
        Product(name: "Маш вареный", category: "Бобовые", proteins: 7, fats: 0.4, carbohydrates: 19.2, calories: 105),
        Product(name: "Нут", category: "Бобовые", proteins: 20.5, fats: 4.3, carbohydrates: 63, calories: 360),
        Product(name: "Нут вареный", category: "Бобовые", proteins: 8.9, fats: 2.6, carbohydrates: 27.4, calories: 164),
        Product(name: "Соя зерно", category: "Бобовые", proteins: 36.7, fats: 17.8, carbohydrates: 17.3, calories: 364),
        Product(name: "Соевые бобы", category: "Бобовые", proteins: 36.4, fats: 19.9, carbohydrates: 30.1, calories: 446),
        Product(name: "Соевые бобы вареные", category: "Бобовые", proteins: 16.6, fats: 8.9, carbohydrates: 9.9, calories: 173),
        Product(name: "Фасоль обыкновенная красная, все виды", category: "Бобовые", proteins: 23.5, fats: 0.8, carbohydrates: 60, calories: 333),
        Product(name: "Фасоль красная вареная", category: "Бобовые", proteins: 8.7, fats: 0.5, carbohydrates: 22.8, calories: 127),
        Product(name: "Фасоль стручковая", category: "Бобовые", proteins: 2.5, fats: 0.3, carbohydrates: 3, calories: 23),
        Product(name: "Чечевица", category: "Бобовые", proteins: 24.6, fats: 1.1, carbohydrates: 63.4, calories: 352),
        Product(name: "Чечевица вареная", category: "Бобовые", proteins: 9, fats: 0.4, carbohydrates: 20.1, calories: 116),
        Product(name: "Чечевица красная", category: "Бобовые", proteins: 21.6, fats: 1.1, carbohydrates: 48, calories: 314),
        Product(name: "Чечевица красная колотая персидская (\"Мистраль\")", category: "Бобовые", proteins: 24.7, fats: 1.2, carbohydrates: 62.5, calories: 328),
        Product(name: "Амарант крупа", category: "Бобовые", proteins: 13.6, fats: 7, carbohydrates: 58.6, calories: 371),
        Product(name: "Амарант вареный", category: "Бобовые", proteins: 3.8, fats: 1.6, carbohydrates: 16.6, calories: 102),
        Product(name: "Киноа крупа", category: "Бобовые", proteins: 14.1, fats: 6.1, carbohydrates: 57.2, calories: 368),
        Product(name: "Киноа вареная", category: "Бобовые", proteins: 4.4, fats: 1.9, carbohydrates: 18.5, calories: 120)
    ],
    "Молочные продукты": [
           Product(name: "Молоко коровье нежирное", category: "Молочные продукты", proteins: 3, fats: 0.05, carbohydrates: 4.9, calories: 32),
           Product(name: "Молоко 1,5% жирности", category: "Молочные продукты", proteins: 3, fats: 1.5, carbohydrates: 4.8, calories: 45),
           Product(name: "Молоко 2,5%", category: "Молочные продукты", proteins: 2.9, fats: 2.5, carbohydrates: 4.8, calories: 54),
           Product(name: "Молоко 3,2%", category: "Молочные продукты", proteins: 2.9, fats: 3.2, carbohydrates: 4.7, calories: 60),
           Product(name: "Сливки 10%", category: "Молочные продукты", proteins: 2.7, fats: 10, carbohydrates: 4.4, calories: 119),
           Product(name: "Сливки 20%", category: "Молочные продукты", proteins: 2.5, fats: 20, carbohydrates: 4, calories: 205),
           Product(name: "Творог нежирный", category: "Молочные продукты", proteins: 22, fats: 0.6, carbohydrates: 3.3, calories: 110),
           Product(name: "Творог 5%", category: "Молочные продукты", proteins: 21, fats: 5, carbohydrates: 3, calories: 145),
           Product(name: "Творог 9%", category: "Молочные продукты", proteins: 18, fats: 9, carbohydrates: 3, calories: 169),
           Product(name: "Творог 18%", category: "Молочные продукты", proteins: 15, fats: 18, carbohydrates: 2.8, calories: 236),
           Product(name: "Сметана 10%", category: "Молочные продукты", proteins: 2.7, fats: 10, carbohydrates: 3.9, calories: 119),
           Product(name: "Сметана 20%", category: "Молочные продукты", proteins: 2.5, fats: 20, carbohydrates: 3.4, calories: 206),
           Product(name: "Сметана 30%", category: "Молочные продукты", proteins: 2.3, fats: 30, carbohydrates: 3.1, calories: 293),
           Product(name: "Кефир нежирный", category: "Молочные продукты", proteins: 3, fats: 0.05, carbohydrates: 4, calories: 31),
           Product(name: "Кефир 1%", category: "Молочные продукты", proteins: 3, fats: 1, carbohydrates: 4, calories: 40),
           Product(name: "Кефир 2,5%", category: "Молочные продукты", proteins: 2.9, fats: 2.5, carbohydrates: 4, calories: 53),
           Product(name: "Кефир 3,2%", category: "Молочные продукты", proteins: 2.9, fats: 3.2, carbohydrates: 4, calories: 59),
           Product(name: "Брынза из коровьего молока", category: "Молочные продукты", proteins: 22.1, fats: 19.2, carbohydrates: 0.4, calories: 262),
           Product(name: "Сыр \"Адыгейский\"", category: "Молочные продукты", proteins: 19.8, fats: 19.8, carbohydrates: 1.5, calories: 264),
           Product(name: "Сыр \"Гауда\"", category: "Молочные продукты", proteins: 25, fats: 27, carbohydrates: 2, calories: 356),
           Product(name: "Сыр \"Голландский\" брусковый", category: "Молочные продукты", proteins: 26, fats: 26.8, carbohydrates: 0, calories: 352),
           Product(name: "Сыр \"Голландский\" круглый", category: "Молочные продукты", proteins: 23.7, fats: 30.4, carbohydrates: 0, calories: 375),
           Product(name: "Сыр \"Ламбер\"", category: "Молочные продукты", proteins: 23.7, fats: 30.5, carbohydrates: 0, calories: 377),
           Product(name: "Сыр \"Ламбер\" сливочный", category: "Молочные продукты", proteins: 23.7, fats: 32.5, carbohydrates: 0, calories: 395),
           Product(name: "Сыр \"Маасдам\"", category: "Молочные продукты", proteins: 23.5, fats: 26, carbohydrates: 0, calories: 350),
           Product(name: "Сыр моцарелла из цельного молока", category: "Молочные продукты", proteins: 22.2, fats: 22.3, carbohydrates: 2.2, calories: 300),
           Product(name: "Сыр \"Пармезан\"", category: "Молочные продукты", proteins: 37.8, fats: 27.3, carbohydrates: 3.4, calories: 415),
           Product(name: "Сыр \"Российский\"", category: "Молочные продукты", proteins: 23.2, fats: 29.5, carbohydrates: 0, calories: 364),
           Product(name: "Сыр рикотта из цельного молока", category: "Молочные продукты", proteins: 11.3, fats: 13, carbohydrates: 3, calories: 174),
           Product(name: "Сулугуни", category: "Молочные продукты", proteins: 20.5, fats: 22, carbohydrates: 0.4, calories: 286),
           Product(name: "Сыр \"Тильзитер\"", category: "Молочные продукты", proteins: 24.4, fats: 26, carbohydrates: 1.9, calories: 340),
           Product(name: "Сыр \"Фета\"", category: "Молочные продукты", proteins: 14.2, fats: 21.3, carbohydrates: 4, calories: 264),
           Product(name: "Сыр \"Эдам\"", category: "Молочные продукты", proteins: 25, fats: 27.8, carbohydrates: 1.4, calories: 357),
           Product(name: "Сыр плавленый", category: "Молочные продукты", proteins: 16.8, fats: 11.2, carbohydrates: 23.8, calories: 257),
           Product(name: "Сыр \"Viola\"", category: "Молочные продукты", proteins: 11, fats: 28, carbohydrates: 2, calories: 305),
           Product(name: "Йогурт \"Активиа\" разных видов", category: "Молочные продукты", proteins: 3.8, fats: 2.9, carbohydrates: 14, calories: 97),
           Product(name: "Йогурт греческий", category: "Молочные продукты", proteins: 5, fats: 3.2, carbohydrates: 3.5, calories: 66),
           Product(name: "\"Actimel\" разных видов", category: "Молочные продукты", proteins: 2.7, fats: 1.5, carbohydrates: 10.5, calories: 71)
       ],
    "Мясо": [
           Product(name: "Говядина 1 категории", category: "Мясо", proteins: 18.6, fats: 16, carbohydrates: 0, calories: 218),
           Product(name: "Говядина 2 категории", category: "Мясо", proteins: 20, fats: 9.8, carbohydrates: 0, calories: 168),
           Product(name: "Говядина, вырезка", category: "Мясо", proteins: 22.2, fats: 7.1, carbohydrates: 0, calories: 158),
           Product(name: "Телятина 1 категории", category: "Мясо", proteins: 19.7, fats: 2, carbohydrates: 0, calories: 97),
           Product(name: "Свинина жирная", category: "Мясо", proteins: 11.7, fats: 49.3, carbohydrates: 0, calories: 491),
           Product(name: "Свинина мясная", category: "Мясо", proteins: 14.3, fats: 33.3, carbohydrates: 0, calories: 357),
           Product(name: "Свинина, вырезка", category: "Мясо", proteins: 19.4, fats: 7.1, carbohydrates: 0, calories: 142),
           Product(name: "Баранина 1 категории", category: "Мясо", proteins: 15.6, fats: 16.3, carbohydrates: 0, calories: 209),
           Product(name: "Баранина 2 категории", category: "Мясо", proteins: 19.8, fats: 9.6, carbohydrates: 0, calories: 166),
           Product(name: "Конина", category: "Мясо", proteins: 20.2, fats: 7, carbohydrates: 0, calories: 187),
           Product(name: "Язык говяжий", category: "Мясо", proteins: 16, fats: 12.1, carbohydrates: 2.2, calories: 173),
           Product(name: "Язык свиной", category: "Мясо", proteins: 15.9, fats: 16, carbohydrates: 2.1, calories: 208),
           Product(name: "Печень говяжья", category: "Мясо", proteins: 17.9, fats: 3.7, carbohydrates: 5.3, calories: 127),
           Product(name: "Печень свиная", category: "Мясо", proteins: 18.8, fats: 3.8, carbohydrates: 4.7, calories: 109),
           Product(name: "Кролик", category: "Мясо", proteins: 21.2, fats: 11, carbohydrates: 0, calories: 183),
           Product(name: "Кабан", category: "Мясо", proteins: 21.5, fats: 3.3, carbohydrates: 0, calories: 122),
           Product(name: "Лось", category: "Мясо", proteins: 23, fats: 1.5, carbohydrates: 0, calories: 111),
           Product(name: "Оленина", category: "Мясо", proteins: 19.5, fats: 8.5, carbohydrates: 0, calories: 155)
       ],
       "Птица": [
           Product(name: "Бройлеры (цыплята) 1 кат.", category: "Птица", proteins: 18.7, fats: 16.1, carbohydrates: 0, calories: 220),
           Product(name: "Бройлеры (цыплята) 2 кат.", category: "Птица", proteins: 19.7, fats: 11.2, carbohydrates: 0, calories: 180),
           Product(name: "Курица 1 кат.", category: "Птица", proteins: 18.2, fats: 18.4, carbohydrates: 0, calories: 238),
           Product(name: "Курица 2 кат.", category: "Птица", proteins: 21.2, fats: 8.2, carbohydrates: 0, calories: 159),
           Product(name: "Куриная грудка", category: "Птица", proteins: 23.6, fats: 1.9, carbohydrates: 0, calories: 113),
           Product(name: "Куриные окорочка", category: "Птица", proteins: 16.8, fats: 10.2, carbohydrates: 0, calories: 158),
           Product(name: "Куриная печень", category: "Птица", proteins: 19.1, fats: 6.3, carbohydrates: 0.6, calories: 136),
           Product(name: "Куриное сердце", category: "Птица", proteins: 15.8, fats: 10.3, carbohydrates: 0.8, calories: 159),
           Product(name: "Индейка", category: "Птица", proteins: 19.5, fats: 22, carbohydrates: 0, calories: 276),
           Product(name: "Индейка, грудка", category: "Птица", proteins: 23.6, fats: 1.5, carbohydrates: 0, calories: 114),
           Product(name: "Индейка, фарш", category: "Птица", proteins: 20, fats: 8, carbohydrates: 0.5, calories: 161),
           Product(name: "Утка домашняя, мясо и кожа", category: "Птица", proteins: 15.8, fats: 38, carbohydrates: 0, calories: 405),
           Product(name: "Утка дикая, мясо и кожа", category: "Птица", proteins: 17.4, fats: 15.2, carbohydrates: 0, calories: 211),
           Product(name: "Утка дикая, мясо", category: "Птица", proteins: 19.8, fats: 4.3, carbohydrates: 0, calories: 123),
           Product(name: "Перепел, мясо и кожа", category: "Птица", proteins: 19.6, fats: 12, carbohydrates: 0, calories: 192),
           Product(name: "Страусиное мясо", category: "Птица", proteins: 21.8, fats: 2.3, carbohydrates: 0, calories: 114),
           Product(name: "Фазан, мясо и кожа", category: "Птица", proteins: 22.7, fats: 9.3, carbohydrates: 0, calories: 181),
           Product(name: "Фазан, грудка", category: "Птица", proteins: 24.3, fats: 3.2, carbohydrates: 0, calories: 133),
       ],
    
        "Колбаса, сосиски, копченности": [
            Product(name: "Колбаса вареная Диетическая", category: "Колбаса, сосиски, копченности", proteins: 12.1, fats: 13.5, carbohydrates: 0, calories: 170),
            Product(name: "Колбаса вареная Докторская", category: "Колбаса, сосиски, копченности", proteins: 12.8, fats: 22.2, carbohydrates: 1.5, calories: 257),
            Product(name: "Колбаса вареная Любительская", category: "Колбаса, сосиски, копченности", proteins: 12.2, fats: 28, carbohydrates: 0.1, calories: 301),
            Product(name: "Колбаса вареная Молочная", category: "Колбаса, сосиски, копченности", proteins: 11.7, fats: 22.8, carbohydrates: 0.2, calories: 252),
            Product(name: "Колбаса вареная Московская", category: "Колбаса, сосиски, копченности", proteins: 11.5, fats: 21.8, carbohydrates: 2, calories: 250),
            Product(name: "Колбаса вареная Русская", category: "Колбаса, сосиски, копченности", proteins: 11.5, fats: 27.9, carbohydrates: 1.7, calories: 302),
            Product(name: "Колбаса варено-копченая Московская", category: "Колбаса, сосиски, копченности", proteins: 19.1, fats: 36.6, carbohydrates: 0.2, calories: 406),
            Product(name: "Колбаса варено-копченая Сервелат", category: "Колбаса, сосиски, копченности", proteins: 16.1, fats: 40.1, carbohydrates: 0, calories: 425),
            Product(name: "Колбаса полукопченая Краковская", category: "Колбаса, сосиски, копченности", proteins: 16.2, fats: 44.6, carbohydrates: 0, calories: 466),
            Product(name: "Колбаса полукопченая Одесская", category: "Колбаса, сосиски, копченности", proteins: 14.8, fats: 38.1, carbohydrates: 0.3, calories: 402),
            Product(name: "Колбаса сырокопченая Брауншвейгская", category: "Колбаса, сосиски, копченности", proteins: 27.7, fats: 42.2, carbohydrates: 0.2, calories: 491),
            Product(name: "Колбаса сырокопченая Московская", category: "Колбаса, сосиски, копченности", proteins: 24.8, fats: 41.5, carbohydrates: 0, calories: 473),
            Product(name: "Колбаса сырокопченая Свиная", category: "Колбаса, сосиски, копченности", proteins: 13, fats: 57, carbohydrates: 0.2, calories: 566),
            Product(name: "Колбаса сырокопченая Зернистая", category: "Колбаса, сосиски, копченности", proteins: 9.9, fats: 62.8, carbohydrates: 0.3, calories: 606),
            Product(name: "Колбаса ливерная Ливерная", category: "Колбаса, сосиски, копченности", proteins: 14.4, fats: 28.5, carbohydrates: 2.2, calories: 326),
            Product(name: "Грудинка сырокопченая", category: "Колбаса, сосиски, копченности", proteins: 8.9, fats: 63.3, carbohydrates: 0, calories: 605),
            Product(name: "Корейка сырокопченая", category: "Колбаса, сосиски, копченности", proteins: 10.5, fats: 47.4, carbohydrates: 0, calories: 469),
            Product(name: "Ветчина Рубленая", category: "Колбаса, сосиски, копченности", proteins: 16.3, fats: 20.7, carbohydrates: 1.8, calories: 263),
            Product(name: "Сосиски Молочные", category: "Колбаса, сосиски, копченности", proteins: 11, fats: 23.9, carbohydrates: 0.4, calories: 261),
            Product(name: "Сосиски Говяжьи", category: "Колбаса, сосиски, копченности", proteins: 10.4, fats: 20.1, carbohydrates: 0.8, calories: 226),
            Product(name: "Сосиски Свиные", category: "Колбаса, сосиски, копченности", proteins: 9.5, fats: 34.3, carbohydrates: 0, calories: 342),
            Product(name: "Сосиски Куриные", category: "Колбаса, сосиски, копченности", proteins: 10.8, fats: 22.4, carbohydrates: 4.2, calories: 259),
            Product(name: "Сардельки Говяжьи", category: "Колбаса, сосиски, копченности", proteins: 11.4, fats: 18.2, carbohydrates: 1.3, calories: 215),
            Product(name: "Сардельки Свиные", category: "Колбаса, сосиски, копченности", proteins: 10.1, fats: 31.6, carbohydrates: 1.8, calories: 322),
            Product(name: "Шпикачки", category: "Колбаса, сосиски, копченности", proteins: 10, fats: 33, carbohydrates: 0, calories: 337),
            Product(name: "Говядина тушеная консервированная", category: "Колбаса, сосиски, копченности", proteins: 16.8, fats: 17, carbohydrates: 0.2, calories: 220),
            Product(name: "Свинина тушеная консервированная", category: "Колбаса, сосиски, копченности", proteins: 14.9, fats: 32.2, carbohydrates: 0.2, calories: 349)
        ],

    "Рыба и морепродукты": [
        Product(name: "Аргентина", category: "Рыба и морепродукты", proteins: 17.6, fats: 2, carbohydrates: 0, calories: 88),
        Product(name: "Амур белый", category: "Рыба и морепродукты", proteins: 18.6, fats: 5.3, carbohydrates: 0, calories: 134),
        Product(name: "Бычок", category: "Рыба и морепродукты", proteins: 17.5, fats: 2, carbohydrates: 0, calories: 88),
        Product(name: "Вобла", category: "Рыба и морепродукты", proteins: 18, fats: 2.8, carbohydrates: 0, calories: 95),
        Product(name: "Горбуша", category: "Рыба и морепродукты", proteins: 20.5, fats: 6.5, carbohydrates: 0, calories: 140),
        Product(name: "Дорадо", category: "Рыба и морепродукты", proteins: 18, fats: 3, carbohydrates: 0, calories: 96),
        Product(name: "Зубатка пестрая", category: "Рыба и морепродукты", proteins: 19.6, fats: 5.3, carbohydrates: 0, calories: 126),
        Product(name: "Кальмар", category: "Рыба и морепродукты", proteins: 18, fats: 2.2, carbohydrates: 2, calories: 100),
        Product(name: "Камбала дальневосточная", category: "Рыба и морепродукты", proteins: 15.7, fats: 3, carbohydrates: 0, calories: 90),
        Product(name: "Карась", category: "Рыба и морепродукты", proteins: 17.7, fats: 1.8, carbohydrates: 0, calories: 87),
        Product(name: "Карп", category: "Рыба и морепродукты", proteins: 16, fats: 5.3, carbohydrates: 0, calories: 112),
        Product(name: "Кета", category: "Рыба и морепродукты", proteins: 19, fats: 5.6, carbohydrates: 0, calories: 127),
        Product(name: "Кефаль", category: "Рыба и морепродукты", proteins: 21, fats: 0.4, carbohydrates: 0, calories: 124),
        Product(name: "Кижуч", category: "Рыба и морепродукты", proteins: 21.6, fats: 5.9, carbohydrates: 0, calories: 146),
        Product(name: "Килька балтийская", category: "Рыба и морепродукты", proteins: 14.1, fats: 9, carbohydrates: 0, calories: 137),
        Product(name: "Килька каспийская", category: "Рыба и морепродукты", proteins: 18.5, fats: 13.1, carbohydrates: 0, calories: 192),
        Product(name: "Китовое мясо", category: "Рыба и морепродукты", proteins: 22.5, fats: 3.2, carbohydrates: 0, calories: 119),
        Product(name: "Краб камчатский, мясо", category: "Рыба и морепродукты", proteins: 18.2, fats: 1, carbohydrates: 0, calories: 82),
        Product(name: "Креветки", category: "Рыба и морепродукты", proteins: 17.0, fats: 0.6, carbohydrates: 0, calories: 80),
        Product(name: "Лангуст", category: "Рыба и морепродукты", proteins: 18.8, fats: 1.3, carbohydrates: 0.5, calories: 89),
        Product(name: "Лангуст вареный", category: "Рыба и морепродукты", proteins: 20.5, fats: 0.7, carbohydrates: 0.3, calories: 90),
        Product(name: "Ледяная рыба", category: "Рыба и морепродукты", proteins: 15.5, fats: 1.4, carbohydrates: 0, calories: 75),
        Product(name: "Лемонема", category: "Рыба и морепродукты", proteins: 15.9, fats: 0.4, carbohydrates: 0, calories: 67),
        Product(name: "Лещ", category: "Рыба и морепродукты", proteins: 17.1, fats: 4.1, carbohydrates: 0, calories: 105),
        Product(name: "Лобстер", category: "Рыба и морепродукты", proteins: 18.8, fats: 0.9, carbohydrates: 0.5, calories: 90),
        Product(name: "Лосось атлантический (семга)", category: "Рыба и морепродукты", proteins: 20, fats: 8.1, carbohydrates: 0, calories: 153),
        Product(name: "Лосось", category: "Рыба и морепродукты", proteins: 19.8, fats: 6.3, carbohydrates: 0, calories: 142),
        Product(name: "Макрурус", category: "Рыба и морепродукты", proteins: 13.2, fats: 0.8, carbohydrates: 0, calories: 60),
        Product(name: "Мидии", category: "Рыба и морепродукты", proteins: 11.5, fats: 2, carbohydrates: 3.3, calories: 77),
        Product(name: "Минтай", category: "Рыба и морепродукты", proteins: 15.9, fats: 0.9, carbohydrates: 0, calories: 72),
        Product(name: "Мойва весенняя", category: "Рыба и морепродукты", proteins: 13.1, fats: 7.1, carbohydrates: 0, calories: 116),
        Product(name: "Мойва осенняя", category: "Рыба и морепродукты", proteins: 13.6, fats: 18.1, carbohydrates: 0, calories: 217),
        Product(name: "Молоки рыб", category: "Рыба и морепродукты", proteins: 16, fats: 2.9, carbohydrates: 0, calories: 90),
        Product(name: "Морской гребешок", category: "Рыба и морепродукты", proteins: 17, fats: 2, carbohydrates: 3, calories: 92),
        Product(name: "Навага", category: "Рыба и морепродукты", proteins: 19.2, fats: 1.6, carbohydrates: 0, calories: 91),
        Product(name: "Налим", category: "Рыба и морепродукты", proteins: 18.8, fats: 0.6, carbohydrates: 0, calories: 81),
        Product(name: "Нерка красная", category: "Рыба и морепродукты", proteins: 20.3, fats: 8.4, carbohydrates: 0, calories: 157),
        Product(name: "Окунь морской", category: "Рыба и морепродукты", proteins: 18.2, fats: 3.3, carbohydrates: 0, calories: 103),
        Product(name: "Окунь речной", category: "Рыба и морепродукты", proteins: 18.5, fats: 0.9, carbohydrates: 0, calories: 82),
        Product(name: "Омар", category: "Рыба и морепродукты", proteins: 18.8, fats: 1.3, carbohydrates: 0.5, calories: 89),
        Product(name: "Омар вареный", category: "Рыба и морепродукты", proteins: 20.5, fats: 0.7, carbohydrates: 0.3, calories: 90),
        Product(name: "Осетр каспийский", category: "Рыба и морепродукты", proteins: 16.4, fats: 10.9, carbohydrates: 0, calories: 164),
        Product(name: "Осетр", category: "Рыба и морепродукты", proteins: 15.8, fats: 15.4, carbohydrates: 0, calories: 202),
        Product(name: "Палтус белокорый", category: "Рыба и морепродукты", proteins: 18.9, fats: 3, carbohydrates: 0, calories: 103),
        Product(name: "Пангасиус", category: "Рыба и морепродукты", proteins: 15.7, fats: 4.8, carbohydrates: 0, calories: 112),
        Product(name: "Петрашка", category: "Рыба и морепродукты", proteins: 19.8, fats: 1.2, carbohydrates: 0, calories: 92),
        Product(name: "Пикуля", category: "Рыба и морепродукты", proteins: 20.5, fats: 2, carbohydrates: 0, calories: 110)
    ],
    "Рыба соленая, копченая, вяленая, икра": [
        Product(name: "Вобла вяленая", category: "Рыба соленая, копченая, вяленая, икра", proteins: 46.4, fats: 5.5, carbohydrates: 0, calories: 235),
        Product(name: "Горбуша горячего копчения", category: "Рыба соленая, копченая, вяленая, икра", proteins: 23.2, fats: 7.6, carbohydrates: 0, calories: 161),
        Product(name: "Горбуша соленая", category: "Рыба соленая, копченая, вяленая, икра", proteins: 22.1, fats: 9.0, carbohydrates: 0, calories: 169),
        Product(name: "Кальмары сушеные", category: "Рыба соленая, копченая, вяленая, икра", proteins: 62, fats: 2, carbohydrates: 5, calories: 286),
        Product(name: "Кета соленая", category: "Рыба соленая, копченая, вяленая, икра", proteins: 24.3, fats: 9.6, carbohydrates: 0, calories: 184),
        Product(name: "Килька балтийская горячего копчения", category: "Рыба соленая, копченая, вяленая, икра", proteins: 21.3, fats: 8.5, carbohydrates: 0, calories: 162),
        Product(name: "Килька балтийская соленая", category: "Рыба соленая, копченая, вяленая, икра", proteins: 17.1, fats: 7.6, carbohydrates: 0, calories: 137),
        Product(name: "Килька пряного посола", category: "Рыба соленая, копченая, вяленая, икра", proteins: 14.8, fats: 10.5, carbohydrates: 0, calories: 154),
        Product(name: "Крабовые палочки", category: "Рыба соленая, копченая, вяленая, икра", proteins: 6.2, fats: 0.38, carbohydrates: 10, calories: 70),
        Product(name: "Икра красная лососевая", category: "Рыба соленая, копченая, вяленая, икра", proteins: 32, fats: 15, carbohydrates: 0, calories: 263),
        Product(name: "Икра минтая пробойная", category: "Рыба соленая, копченая, вяленая, икра", proteins: 27.9, fats: 1.8, carbohydrates: 1.1, calories: 132),
        Product(name: "Икра мойвы \"Санта Бремор\"", category: "Рыба соленая, копченая, вяленая, икра", proteins: 8.1, fats: 36.9, carbohydrates: 0, calories: 365),
        Product(name: "Икра сельди", category: "Рыба соленая, копченая, вяленая, икра", proteins: 31.6, fats: 10.3, carbohydrates: 0, calories: 222),
        Product(name: "Икра черная осетровая зернистая", category: "Рыба соленая, копченая, вяленая, икра", proteins: 28.4, fats: 9.3, carbohydrates: 0.6, calories: 200),
        Product(name: "Икра осетровая паюсная", category: "Рыба соленая, копченая, вяленая, икра", proteins: 38.2, fats: 14.5, carbohydrates: 1.5, calories: 289),
        Product(name: "Икра щучья", category: "Рыба соленая, копченая, вяленая, икра", proteins: 17.3, fats: 2, carbohydrates: 0, calories: 87),
        Product(name: "Лосось соленый", category: "Рыба соленая, копченая, вяленая, икра", proteins: 21, fats: 20.5, carbohydrates: 0, calories: 269),
        Product(name: "Лещ вяленый", category: "Рыба соленая, копченая, вяленая, икра", proteins: 42, fats: 5.9, carbohydrates: 0, calories: 221),
        Product(name: "Лещ горячего копчения", category: "Рыба соленая, копченая, вяленая, икра", proteins: 32.8, fats: 4.5, carbohydrates: 0, calories: 172),
        Product(name: "Лещ холодного копчения", category: "Рыба соленая, копченая, вяленая, икра", proteins: 29.7, fats: 4.6, carbohydrates: 0, calories: 160),
        Product(name: "Масляная рыба копченая", category: "Рыба соленая, копченая, вяленая, икра", proteins: 18, fats: 12, carbohydrates: 0, calories: 180),
        Product(name: "Мойва копченая", category: "Рыба соленая, копченая, вяленая, икра", proteins: 18, fats: 22, carbohydrates: 0, calories: 270),
        Product(name: "Окунь морской горячего копчения", category: "Рыба соленая, копченая, вяленая, икра", proteins: 23.5, fats: 8, carbohydrates: 0, calories: 166),
        Product(name: "Осетр холодного копчения, балык", category: "Рыба соленая, копченая, вяленая, икра", proteins: 20.4, fats: 12.5, carbohydrates: 0, calories: 194),
        Product(name: "Салака копченая", category: "Рыба соленая, копченая, вяленая, икра", proteins: 25.4, fats: 5.6, carbohydrates: 0, calories: 152),
        Product(name: "Сельдь горячего копчения", category: "Рыба соленая, копченая, вяленая, икра", proteins: 21.8, fats: 14.3, carbohydrates: 0, calories: 215),
        Product(name: "Сельдь атлантическая среднесоленая", category: "Рыба соленая, копченая, вяленая, икра", proteins: 17, fats: 8.5, carbohydrates: 0, calories: 145),
        Product(name: "Сельдь тихоокеанская среднесоленая", category: "Рыба соленая, копченая, вяленая, икра", proteins: 17.4, fats: 17.1, carbohydrates: 0, calories: 224),
        Product(name: "Сельдь соленая", category: "Рыба соленая, копченая, вяленая, икра", proteins: 19.8, fats: 15.4, carbohydrates: 0, calories: 217),
        Product(name: "Семга соленая потрошеная с головой", category: "Рыба соленая, копченая, вяленая, икра", proteins: 22.5, fats: 12.5, carbohydrates: 0, calories: 202),
        Product(name: "Семга копченая", category: "Рыба соленая, копченая, вяленая, икра", proteins: 22.5, fats: 12.5, carbohydrates: 0, calories: 202),
        Product(name: "Скумбрия горячего копчения", category: "Рыба соленая, копченая, вяленая, икра", proteins: 22.1, fats: 23.8, carbohydrates: 0, calories: 307),
        Product(name: "Скумбрия холодного копчения", category: "Рыба соленая, копченая, вяленая, икра", proteins: 23.4, fats: 6.4, carbohydrates: 0, calories: 150),
        Product(name: "Форель копченая", category: "Рыба соленая, копченая, вяленая, икра", proteins: 26, fats: 3.1, carbohydrates: 0.5, calories: 132),
        Product(name: "Форель слабосоленая", category: "Рыба соленая, копченая, вяленая, икра", proteins: 20.6, fats: 10.1, carbohydrates: 0, calories: 186),
        Product(name: "Форель слабосоленая жирная", category: "Рыба соленая, копченая, вяленая, икра", proteins: 23, fats: 15, carbohydrates: 0, calories: 227),
        Product(name: "Хамса соленая", category: "Рыба соленая, копченая, вяленая, икра", proteins: 21.2, fats: 9, carbohydrates: 0, calories: 166)
    ],
        "Консервы рыбные": [
            Product(name: "Бычки в томатном соусе", category: "Консервы рыбные", proteins: 17.5, fats: 2, carbohydrates: 0, calories: 88),
            Product(name: "Горбуша натуральная", category: "Консервы рыбные", proteins: 20.9, fats: 5.8, carbohydrates: 0, calories: 136),
            Product(name: "Горбуша в томатном соусе", category: "Консервы рыбные", proteins: 15, fats: 6, carbohydrates: 4.1, calories: 130),
            Product(name: "Кальмары", category: "Консервы рыбные", proteins: 15, fats: 1.5, carbohydrates: 1.7, calories: 76),
            Product(name: "Килька в томатном соусе", category: "Консервы рыбные", proteins: 14, fats: 12, carbohydrates: 4.5, calories: 182),
            Product(name: "Крабы", category: "Консервы рыбные", proteins: 18.7, fats: 1.1, carbohydrates: 0.1, calories: 85),
            Product(name: "Лосось", category: "Консервы рыбные", proteins: 20.6, fats: 6.3, carbohydrates: 0, calories: 144),
            Product(name: "Мидии", category: "Консервы рыбные", proteins: 17.5, fats: 2, carbohydrates: 0, calories: 88),
            Product(name: "Морская капуста", category: "Консервы рыбные", proteins: 0.8, fats: 5.1, carbohydrates: 0, calories: 49),
            Product(name: "Печень минтая", category: "Консервы рыбные", proteins: 6, fats: 50, carbohydrates: 0, calories: 474),
            Product(name: "Печень трески", category: "Консервы рыбные", proteins: 4.2, fats: 65.7, carbohydrates: 1.2, calories: 613),
            Product(name: "Сайра бланшированная в масле", category: "Консервы рыбные", proteins: 18.3, fats: 23.3, carbohydrates: 0, calories: 283),
            Product(name: "Сардины с добавлением масла", category: "Консервы рыбные", proteins: 19, fats: 18, carbohydrates: 0, calories: 238),
            Product(name: "Сардины в масле", category: "Консервы рыбные", proteins: 24.1, fats: 13.9, carbohydrates: 0, calories: 221),
            Product(name: "Сардины в томатном соусе", category: "Консервы рыбные", proteins: 17, fats: 9.9, carbohydrates: 1.4, calories: 162),
            Product(name: "Сельдь", category: "Консервы рыбные", proteins: 17.5, fats: 2, carbohydrates: 0, calories: 88),
            Product(name: "Сельдь в растительном масле", category: "Консервы рыбные", proteins: 16.4, fats: 26.5, carbohydrates: 0, calories: 301),
            Product(name: "Скумбрия натуральная", category: "Консервы рыбные", proteins: 17.7, fats: 14.4, carbohydrates: 0, calories: 200),
            Product(name: "Скумбрия в масле", category: "Консервы рыбные", proteins: 14.4, fats: 28.9, carbohydrates: 0, calories: 318),
            Product(name: "Ставрида в масле", category: "Консервы рыбные", proteins: 15.6, fats: 27.4, carbohydrates: 0, calories: 309),
            Product(name: "Ставрида в томатном соусе", category: "Консервы рыбные", proteins: 14.8, fats: 2.3, carbohydrates: 73, calories: 110),
            Product(name: "Тунец натуральный", category: "Консервы рыбные", proteins: 22.5, fats: 0.7, carbohydrates: 0, calories: 96),
            Product(name: "Тунец в масле", category: "Консервы рыбные", proteins: 22, fats: 15.9, carbohydrates: 0, calories: 232),
            Product(name: "Шпроты в масле", category: "Консервы рыбные", proteins: 17.4, fats: 32.4, carbohydrates: 0.4, calories: 363),
            Product(name: "Шпротный паштет", category: "Консервы рыбные", proteins: 12, fats: 14, carbohydrates: 5.3, calories: 195)
        ],
    "Яйцепродукты": [
        Product(name: "Яйцо куриное", category: "Яйцепродукты", proteins: 12.7, fats: 10.9, carbohydrates: 0.7, calories: 157),
        Product(name: "Белок", category: "Яйцепродукты", proteins: 11.1, fats: 0, carbohydrates: 0, calories: 44),
        Product(name: "Желток", category: "Яйцепродукты", proteins: 16.2, fats: 31.2, carbohydrates: 1, calories: 354),
        Product(name: "Яйцо куриное отварное", category: "Яйцепродукты", proteins: 12.7, fats: 11.5, carbohydrates: 0.7, calories: 157),
        Product(name: "Яйцо куриное жареное без масла", category: "Яйцепродукты", proteins: 14.6, fats: 12.6, carbohydrates: 0.8, calories: 174),
        Product(name: "Яйцо перепелиное", category: "Яйцепродукты", proteins: 11.9, fats: 13.1, carbohydrates: 0.6, calories: 168),
        Product(name: "Яйцо гусиное", category: "Яйцепродукты", proteins: 13.9, fats: 13.3, carbohydrates: 1.4, calories: 185),
        Product(name: "Яйцо утиное", category: "Яйцепродукты", proteins: 13.3, fats: 14.5, carbohydrates: 0.1, calories: 185),
        Product(name: "Яйцо страусиное", category: "Яйцепродукты", proteins: 12.2, fats: 11.7, carbohydrates: 0.7, calories: 118),
        Product(name: "Меланж", category: "Яйцепродукты", proteins: 12.7, fats: 11.5, carbohydrates: 0.7, calories: 157),
        Product(name: "Яичный порошок", category: "Яйцепродукты", proteins: 46, fats: 37.3, carbohydrates: 4.5, calories: 542)
    ],
    "Масла, жиры и жировые продукты": [
        Product(name: "Масло сливочное", category: "Масла, жиры и жировые продукты", proteins: 0.5, fats: 78.0, carbohydrates: 0.8, calories: 709),
        Product(name: "Масло сливочное \"Валио\"", category: "Масла, жиры и жировые продукты", proteins: 0.7, fats: 82.0, carbohydrates: 0.7, calories: 740),
        Product(name: "Масло топленое", category: "Масла, жиры и жировые продукты", proteins: 0.2, fats: 99.0, carbohydrates: 0, calories: 892),
        Product(name: "Масло шоколадное", category: "Масла, жиры и жировые продукты", proteins: 1.5, fats: 62.0, carbohydrates: 18.6, calories: 642),
        Product(name: "Масло оливковое", category: "Масла, жиры и жировые продукты", proteins: 0, fats: 99.8, carbohydrates: 0, calories: 898),
        Product(name: "Масло подсолнечное", category: "Масла, жиры и жировые продукты", proteins: 0, fats: 99.9, carbohydrates: 0, calories: 899),
        Product(name: "Маргарин", category: "Масла, жиры и жировые продукты", proteins: 0.3, fats: 82.0, carbohydrates: 0.8, calories: 743),
        Product(name: "Спред", category: "Масла, жиры и жировые продукты", proteins: 0, fats: 40.0, carbohydrates: 0, calories: 360),
        Product(name: "Майонез", category: "Масла, жиры и жировые продукты", proteins: 1.4, fats: 47.0, carbohydrates: 2.6, calories: 450),
        Product(name: "Майонез легкий", category: "Масла, жиры и жировые продукты", proteins: 0.3, fats: 8.0, carbohydrates: 1.9, calories: 110),
        Product(name: "Жир говяжий, свиной, бараний топленые", category: "Масла, жиры и жировые продукты", proteins: 0, fats: 99.7, carbohydrates: 0, calories: 897),
        Product(name: "Жир кулинарный, кондитерский", category: "Масла, жиры и жировые продукты", proteins: 0, fats: 99.7, carbohydrates: 0, calories: 897),
        Product(name: "Жир рыбий", category: "Масла, жиры и жировые продукты", proteins: 0, fats: 100.0, carbohydrates: 0, calories: 902),
        Product(name: "Сало", category: "Масла, жиры и жировые продукты", proteins: 2.4, fats: 89.0, carbohydrates: 0, calories: 797),
        Product(name: "Шпик", category: "Масла, жиры и жировые продукты", proteins: 1.4, fats: 92.8, carbohydrates: 0, calories: 841)
    ],
    "Овощи, зелень": [
        Product(name: "Артишок", category: "Овощи, зелень", proteins: 1.2, fats: 0.1, carbohydrates: 6, calories: 28),
        Product(name: "Базилик", category: "Овощи, зелень", proteins: 2.5, fats: 0.6, carbohydrates: 4.3, calories: 27),
        Product(name: "Баклажаны", category: "Овощи, зелень", proteins: 1.2, fats: 0.1, carbohydrates: 4.5, calories: 24),
        Product(name: "Батат (сладкий картофель)", category: "Овощи, зелень", proteins: 1.6, fats: 0.05, carbohydrates: 17.1, calories: 86),
        Product(name: "Батат отварной без кожуры", category: "Овощи, зелень", proteins: 1.4, fats: 0.14, carbohydrates: 15.2, calories: 76),
        Product(name: "Брюква", category: "Овощи, зелень", proteins: 1.2, fats: 0.1, carbohydrates: 7.7, calories: 37),
        Product(name: "Горчица листовая", category: "Овощи, зелень", proteins: 2.9, fats: 0.4, carbohydrates: 1.5, calories: 27),
        Product(name: "Дайкон", category: "Овощи, зелень", proteins: 1.2, fats: 0, carbohydrates: 4.1, calories: 21),
        Product(name: "Имбирь, корень сырой", category: "Овощи, зелень", proteins: 1.8, fats: 0.75, carbohydrates: 15.8, calories: 80),
        Product(name: "Кабачки", category: "Овощи, зелень", proteins: 0.6, fats: 0.3, carbohydrates: 4.6, calories: 24),
        Product(name: "Капуста белокочанная", category: "Овощи, зелень", proteins: 1.8, fats: 0.1, carbohydrates: 4.7, calories: 28),
        Product(name: "Капуста квашеная", category: "Овощи, зелень", proteins: 1.8, fats: 0.1, carbohydrates: 3, calories: 23),
        Product(name: "Капуста вареная", category: "Овощи, зелень", proteins: 1.4, fats: 0.1, carbohydrates: 4.2, calories: 24),
        Product(name: "Капуста брокколи", category: "Овощи, зелень", proteins: 2.8, fats: 0.37, carbohydrates: 6.6, calories: 34),
        Product(name: "Капуста брокколи вареная", category: "Овощи, зелень", proteins: 2.38, fats: 0.4, carbohydrates: 7.18, calories: 35),
        Product(name: "Капуста брокколизамороженная, вареная", category: "Овощи, зелень", proteins: 3.1, fats: 0.12, carbohydrates: 5.35, calories: 28),
        Product(name: "Капуста брюссельская", category: "Овощи, зелень", proteins: 3.4, fats: 0.3, carbohydrates: 8.9, calories: 43),
        Product(name: "Капуста брюссельскаязамороженная, вареная", category: "Овощи, зелень", proteins: 3.6, fats: 0.4, carbohydrates: 8.3, calories: 42),
        Product(name: "Капуста кольраби", category: "Овощи, зелень", proteins: 2.8, fats: 0.1, carbohydrates: 7.9, calories: 44),
        Product(name: "Капуста краснокочанная", category: "Овощи, зелень", proteins: 0.8, fats: 0.2, carbohydrates: 5.1, calories: 26),
        Product(name: "Капуста пекинская", category: "Овощи, зелень", proteins: 1.2, fats: 0.2, carbohydrates: 2, calories: 16),
        Product(name: "Капуста савойская", category: "Овощи, зелень", proteins: 1.2, fats: 0.1, carbohydrates: 5.6, calories: 28),
        Product(name: "Капуста цветная", category: "Овощи, зелень", proteins: 2.5, fats: 0.3, carbohydrates: 4.2, calories: 30),
        Product(name: "Капуста листовая кале (кейл, Kale)", category: "Овощи, зелень", proteins: 2.8, fats: 0.6, carbohydrates: 6.6, calories: 42),
        Product(name: "Капуста листовая коллардс(Collards)", category: "Овощи, зелень", proteins: 3, fats: 0.6, carbohydrates: 1.4, calories: 32),
        Product(name: "Картофель", category: "Овощи, зелень", proteins: 2, fats: 0.4, carbohydrates: 16.3, calories: 77),
        Product(name: "Картофель отварной", category: "Овощи, зелень", proteins: 2, fats: 0.4, carbohydrates: 15.8, calories: 75),
        Product(name: "Кресс-салат", category: "Овощи, зелень", proteins: 2.3, fats: 0.1, carbohydrates: 0.8, calories: 11),
        Product(name: "Кукуруза сырая", category: "Овощи, зелень", proteins: 3.3, fats: 1.35, carbohydrates: 16.7, calories: 86),
        Product(name: "Лук зеленый", category: "Овощи, зелень", proteins: 1.3, fats: 0.1, carbohydrates: 3.2, calories: 20),
        Product(name: "Лук репчатый", category: "Овощи, зелень", proteins: 1.4, fats: 0.2, carbohydrates: 8.2, calories: 41),
        Product(name: "Лук репчатый красный", category: "Овощи, зелень", proteins: 1.4, fats: 0.1, carbohydrates: 9.1, calories: 42),
        Product(name: "Лук порей", category: "Овощи, зелень", proteins: 2, fats: 0.2, carbohydrates: 6.3, calories: 36),
        Product(name: "Мангольд", category: "Овощи, зелень", proteins: 1.8, fats: 0.2, carbohydrates: 2.1, calories: 19),
        Product(name: "Морковь", category: "Овощи, зелень", proteins: 1.3, fats: 0.1, carbohydrates: 6.9, calories: 35),
        Product(name: "Морковь отварная", category: "Овощи, зелень", proteins: 1.3, fats: 0.1, carbohydrates: 6.4, calories: 33),
        Product(name: "Огурцы грунтовые", category: "Овощи, зелень", proteins: 0.8, fats: 0.1, carbohydrates: 3.6, calories: 16),
        Product(name: "Огурцы маринованные", category: "Овощи, зелень", proteins: 0.8, fats: 0.1, carbohydrates: 2.7, calories: 15),
        Product(name: "Огурцы соленые", category: "Овощи, зелень", proteins: 0.8, fats: 0.1, carbohydrates: 2.5, calories: 13),
        Product(name: "Оливки", category: "Овощи, зелень", proteins: 1, fats: 10.7, carbohydrates: 6, calories: 115),
        Product(name: "Перец сладкий", category: "Овощи, зелень", proteins: 0.9, fats: 0.3, carbohydrates: 5.9, calories: 27),
        Product(name: "Перец сладкий жареный", category: "Овощи, зелень", proteins: 1, fats: 0.4, carbohydrates: 4.9, calories: 31),
        Product(name: "Помидоры", category: "Овощи, зелень", proteins: 0.9, fats: 0.2, carbohydrates: 3.9, calories: 20),
        Product(name: "Помидоры сушеные", category: "Овощи, зелень", proteins: 4.6, fats: 3.3, carbohydrates: 31.8, calories: 258),
        Product(name: "Руккола", category: "Овощи, зелень", proteins: 2.6, fats: 0.7, carbohydrates: 3.7, calories: 25),
        Product(name: "Сельдерей", category: "Овощи, зелень", proteins: 1.5, fats: 0.2, carbohydrates: 3.3, calories: 16),
        Product(name: "Томаты черри", category: "Овощи, зелень", proteins: 0.9, fats: 0.2, carbohydrates: 3.9, calories: 18),
        Product(name: "Тыква", category: "Овощи, зелень", proteins: 1.2, fats: 0.1, carbohydrates: 6.5, calories: 26),
        Product(name: "Тыква запеченная", category: "Овощи, зелень", proteins: 1.1, fats: 0.1, carbohydrates: 6.4, calories: 27),
        Product(name: "Шпинат", category: "Овощи, зелень", proteins: 2.9, fats: 0.4, carbohydrates: 3.6, calories: 23),
        Product(name: "Шпинат вареный", category: "Овощи, зелень", proteins: 3, fats: 0.3, carbohydrates: 3.8, calories: 23),
        Product(name: "Ямс", category: "Овощи, зелень", proteins: 1.5, fats: 0.2, carbohydrates: 27.9, calories: 118)
    ],
    "Грибы": [
        Product(name: "Грибы белые свежие", category: "Грибы", proteins: 3.7, fats: 1.7, carbohydrates: 1.1, calories: 34),
        Product(name: "Грибы белые сушеные", category: "Грибы", proteins: 30.3, fats: 14.3, carbohydrates: 9.0, calories: 286),
        Product(name: "Вешенки свежие", category: "Грибы", proteins: 2.5, fats: 0.3, carbohydrates: 6.5, calories: 3.8),
        Product(name: "Грузди свежие", category: "Грибы", proteins: 1.8, fats: 0.5, carbohydrates: 0.8, calories: 16),
        Product(name: "Лисички", category: "Грибы", proteins: 1.5, fats: 1.0, carbohydrates: 1.0, calories: 19),
        Product(name: "Опята", category: "Грибы", proteins: 2.2, fats: 1.2, carbohydrates: 0.5, calories: 22),
        Product(name: "Подберезовики", category: "Грибы", proteins: 2.1, fats: 0.8, carbohydrates: 1.2, calories: 20),
        Product(name: "Подберезовики сушеные", category: "Грибы", proteins: 23.5, fats: 9.2, carbohydrates: 14.3, calories: 231),
        Product(name: "Подосиновики", category: "Грибы", proteins: 3.3, fats: 0.5, carbohydrates: 1.2, calories: 22),
        Product(name: "Подосиновики сушеные", category: "Грибы", proteins: 35.4, fats: 5.4, carbohydrates: 33.2, calories: 315),
        Product(name: "Сморчки", category: "Грибы", proteins: 1.7, fats: 0.3, carbohydrates: 4.2, calories: 27),
        Product(name: "Сыроежки", category: "Грибы", proteins: 1.7, fats: 0.7, carbohydrates: 1.5, calories: 19),
        Product(name: "Шампиньоны", category: "Грибы", proteins: 4.3, fats: 1.0, carbohydrates: 0.1, calories: 27)
    ],
    "Овощные консервы": [
        Product(name: "Икра баклажанная", category: "Овощные консервы", proteins: 1.7, fats: 13.3, carbohydrates: 5.1, calories: 148),
        Product(name: "Икра кабачковая", category: "Овощные консервы", proteins: 1.6, fats: 8.15, carbohydrates: 7.0, calories: 109.5), // Среднее значение
        Product(name: "Горошек зеленый", category: "Овощные консервы", proteins: 3.1, fats: 0.2, carbohydrates: 6.5, calories: 40),
        Product(name: "Кукуруза сладкая", category: "Овощные консервы", proteins: 2.95, fats: 0.65, carbohydrates: 17.85, calories: 92), // Среднее значение
        Product(name: "Огурцы маринованные", category: "Овощные консервы", proteins: 0.8, fats: 1.3, carbohydrates: 0.0, calories: 16),
        Product(name: "Помидоры маринованные", category: "Овощные консервы", proteins: 0.5, fats: 0.1, carbohydrates: 2.1, calories: 10),
        Product(name: "Свекла", category: "Овощные консервы", proteins: 1.05, fats: 0.05, carbohydrates: 6.225, calories: 31.5) // Среднее значение
    ],
    "Фрукты, ягоды, бахчевые": [
        Product(name: "Арбуз", category: "Фрукты, ягоды, бахчевые", proteins: 0.6, fats: 0.1, carbohydrates: 5.8, calories: 27),
        Product(name: "Абрикосы", category: "Фрукты, ягоды, бахчевые", proteins: 0.9, fats: 0.1, carbohydrates: 9, calories: 44),
        Product(name: "Авокадо", category: "Фрукты, ягоды, бахчевые", proteins: 2, fats: 14.6, carbohydrates: 8.5, calories: 160),
        Product(name: "Айва", category: "Фрукты, ягоды, бахчевые", proteins: 0.6, fats: 0.5, carbohydrates: 9.6, calories: 48),
        Product(name: "Алыча", category: "Фрукты, ягоды, бахчевые", proteins: 0.2, fats: 0.1, carbohydrates: 7.9, calories: 34),
        Product(name: "Ананас", category: "Фрукты, ягоды, бахчевые", proteins: 0.4, fats: 0.2, carbohydrates: 11.5, calories: 52),
        Product(name: "Апельсины", category: "Фрукты, ягоды, бахчевые", proteins: 0.9, fats: 0.2, carbohydrates: 8.1, calories: 43),
        Product(name: "Банан", category: "Фрукты, ягоды, бахчевые", proteins: 1.5, fats: 0.5, carbohydrates: 21, calories: 96),
        Product(name: "Виноград", category: "Фрукты, ягоды, бахчевые", proteins: 0.6, fats: 0.6, carbohydrates: 15.4, calories: 72),
        Product(name: "Вишня", category: "Фрукты, ягоды, бахчевые", proteins: 0.8, fats: 0.2, carbohydrates: 10.6, calories: 52),
        Product(name: "Гранат", category: "Фрукты, ягоды, бахчевые", proteins: 0.7, fats: 0.6, carbohydrates: 14.5, calories: 72),
        Product(name: "Грейпфрут", category: "Фрукты, ягоды, бахчевые", proteins: 0.7, fats: 0.2, carbohydrates: 6.5, calories: 35),
        Product(name: "Груша", category: "Фрукты, ягоды, бахчевые", proteins: 0.4, fats: 0.3, carbohydrates: 10.3, calories: 47),
        Product(name: "Дуриан", category: "Фрукты, ягоды, бахчевые", proteins: 1.5, fats: 5.3, carbohydrates: 23.3, calories: 147),
        Product(name: "Дыня", category: "Фрукты, ягоды, бахчевые", proteins: 0.6, fats: 0.3, carbohydrates: 7.4, calories: 35),
        Product(name: "Инжир свежий", category: "Фрукты, ягоды, бахчевые", proteins: 0.7, fats: 0.2, carbohydrates: 12, calories: 54),
        Product(name: "Киви", category: "Фрукты, ягоды, бахчевые", proteins: 0.8, fats: 0.4, carbohydrates: 8.1, calories: 47),
        Product(name: "Кумкват", category: "Фрукты, ягоды, бахчевые", proteins: 1.9, fats: 0.9, carbohydrates: 13.4, calories: 71),
        Product(name: "Лимон", category: "Фрукты, ягоды, бахчевые", proteins: 0.9, fats: 0.1, carbohydrates: 3, calories: 34),
        Product(name: "Личи", category: "Фрукты, ягоды, бахчевые", proteins: 0.8, fats: 0.4, carbohydrates: 15.2, calories: 66),
        Product(name: "Манго", category: "Фрукты, ягоды, бахчевые", proteins: 0.8, fats: 0.4, carbohydrates: 13.4, calories: 60),
        Product(name: "Мандарины", category: "Фрукты, ягоды, бахчевые", proteins: 0.8, fats: 0.2, carbohydrates: 7.5, calories: 38),
        Product(name: "Маракуйя", category: "Фрукты, ягоды, бахчевые", proteins: 2.4, fats: 0.4, carbohydrates: 13.4, calories: 68),
        Product(name: "Нектарин", category: "Фрукты, ягоды, бахчевые", proteins: 1.1, fats: 0.3, carbohydrates: 9, calories: 44),
        Product(name: "Папайя", category: "Фрукты, ягоды, бахчевые", proteins: 0.5, fats: 0.26, carbohydrates: 9.1, calories: 43),
        Product(name: "Персик", category: "Фрукты, ягоды, бахчевые", proteins: 0.9, fats: 0.1, carbohydrates: 9.5, calories: 45),
        Product(name: "Помело", category: "Фрукты, ягоды, бахчевые", proteins: 0.8, fats: 0.04, carbohydrates: 8.6, calories: 38),
        Product(name: "Слива", category: "Фрукты, ягоды, бахчевые", proteins: 0.8, fats: 0.3, carbohydrates: 9.6, calories: 49),
        Product(name: "Терн", category: "Фрукты, ягоды, бахчевые", proteins: 1.5, fats: 0.3, carbohydrates: 9.4, calories: 54),
        Product(name: "Фейхоа", category: "Фрукты, ягоды, бахчевые", proteins: 0.7, fats: 0.4, carbohydrates: 8.8, calories: 61),
        Product(name: "Хурма", category: "Фрукты, ягоды, бахчевые", proteins: 0.5, fats: 0.4, carbohydrates: 15.3, calories: 67),
        Product(name: "Черешня", category: "Фрукты, ягоды, бахчевые", proteins: 1.1, fats: 0.4, carbohydrates: 10.6, calories: 52),
        Product(name: "Яблоки", category: "Фрукты, ягоды, бахчевые", proteins: 0.4, fats: 0.4, carbohydrates: 9.8, calories: 47),
        Product(name: "Брусника", category: "Фрукты, ягоды, бахчевые", proteins: 0.7, fats: 0.5, carbohydrates: 8.2, calories: 46),
        Product(name: "Голубика", category: "Фрукты, ягоды, бахчевые", proteins: 1, fats: 0.5, carbohydrates: 6.6, calories: 39),
        Product(name: "Ежевика", category: "Фрукты, ягоды, бахчевые", proteins: 1.5, fats: 0.5, carbohydrates: 4.4, calories: 34),
        Product(name: "Клубника", category: "Фрукты, ягоды, бахчевые", proteins: 0.8, fats: 0.4, carbohydrates: 7.5, calories: 41),
        Product(name: "Клюква", category: "Фрукты, ягоды, бахчевые", proteins: 0.5, fats: 0.2, carbohydrates: 3.7, calories: 28),
        Product(name: "Крыжовник", category: "Фрукты, ягоды, бахчевые", proteins: 0.7, fats: 0.2, carbohydrates: 9.1, calories: 45),
        Product(name: "Малина", category: "Фрукты, ягоды, бахчевые", proteins: 0.8, fats: 0.5, carbohydrates: 8.3, calories: 46),
        Product(name: "Морошка", category: "Фрукты, ягоды, бахчевые", proteins: 0.8, fats: 0.9, carbohydrates: 7.4, calories: 40),
        Product(name: "Облепиха", category: "Фрукты, ягоды, бахчевые", proteins: 1.2, fats: 5.4, carbohydrates: 5.7, calories: 82),
        Product(name: "Смородина белая", category: "Фрукты, ягоды, бахчевые", proteins: 0.5, fats: 0.2, carbohydrates: 8, calories: 42),
        Product(name: "Смородина красная", category: "Фрукты, ягоды, бахчевые", proteins: 0.6, fats: 0.2, carbohydrates: 7.7, calories: 43),
        Product(name: "Смородина черная", category: "Фрукты, ягоды, бахчевые", proteins: 1, fats: 0.4, carbohydrates: 7.3, calories: 44),
        Product(name: "Черника", category: "Фрукты, ягоды, бахчевые", proteins: 1.1, fats: 0.6, carbohydrates: 7.6, calories: 44),
        Product(name: "Шиповник свежий", category: "Фрукты, ягоды, бахчевые", proteins: 1.6, fats: 0.7, carbohydrates: 22.4, calories: 109),
        Product(name: "Шиповник сухой", category: "Фрукты, ягоды, бахчевые", proteins: 3.4, fats: 1.4, carbohydrates: 48.3, calories: 284)
    ],
    "Орехи, семена, сухофрукты": [
        Product(name: "Арахис", category: "Орехи, семена, сухофрукты", proteins: 26.3, fats: 45.2, carbohydrates: 9.9, calories: 552),
        Product(name: "Арахис жареный", category: "Орехи, семена, сухофрукты", proteins: 26, fats: 52, carbohydrates: 13.4, calories: 626),
        Product(name: "Бразильский орех", category: "Орехи, семена, сухофрукты", proteins: 14.3, fats: 67.1, carbohydrates: 4.2, calories: 659),
        Product(name: "Грецкие орехи", category: "Орехи, семена, сухофрукты", proteins: 16.2, fats: 60.8, carbohydrates: 11.1, calories: 656),
        Product(name: "Кедровые орехи", category: "Орехи, семена, сухофрукты", proteins: 13.7, fats: 64.1, carbohydrates: 9.4, calories: 673),
        Product(name: "Кешью", category: "Орехи, семена, сухофрукты", proteins: 18.5, fats: 48.5, carbohydrates: 22.5, calories: 600),
        Product(name: "Кешью жареный", category: "Орехи, семена, сухофрукты", proteins: 17.5, fats: 42.2, carbohydrates: 30.5, calories: 572),
        Product(name: "Кокосовый орех сырой", category: "Орехи, семена, сухофрукты", proteins: 3.3, fats: 33.5, carbohydrates: 6.2, calories: 354),
        Product(name: "Лесной орех (лещина)", category: "Орехи, семена, сухофрукты", proteins: 13, fats: 62.6, carbohydrates: 9.3, calories: 653),
        Product(name: "Миндальный орех", category: "Орехи, семена, сухофрукты", proteins: 18.6, fats: 53.7, carbohydrates: 13, calories: 609),
        Product(name: "Миндальный орех жареный", category: "Орехи, семена, сухофрукты", proteins: 22.4, fats: 55.9, carbohydrates: 12.3, calories: 642),
        Product(name: "Миндальные лепестки", category: "Орехи, семена, сухофрукты", proteins: 22, fats: 58, carbohydrates: 12, calories: 650),
        Product(name: "Орех макадамия", category: "Орехи, семена, сухофрукты", proteins: 7.9, fats: 75.8, carbohydrates: 5.2, calories: 718),
        Product(name: "Орехи пекан", category: "Орехи, семена, сухофрукты", proteins: 9.2, fats: 72, carbohydrates: 4.3, calories: 691),
        Product(name: "Семечки подсолнечника, ядра сушеные", category: "Орехи, семена, сухофрукты", proteins: 20.8, fats: 51.5, carbohydrates: 17.4, calories: 584),
        Product(name: "Семечки тыквенные, ядра сушеные", category: "Орехи, семена, сухофрукты", proteins: 30.2, fats: 49.1, carbohydrates: 9.3, calories: 559),
        Product(name: "Семена конопли очищенные", category: "Орехи, семена, сухофрукты", proteins: 31.6, fats: 48.7, carbohydrates: 4.7, calories: 553),
        Product(name: "Семена конопли неочищенные", category: "Орехи, семена, сухофрукты", proteins: 20.1, fats: 32.5, carbohydrates: 14, calories: 429),
        Product(name: "Семена кунжута", category: "Орехи, семена, сухофрукты", proteins: 19.4, fats: 48.7, carbohydrates: 12.2, calories: 565),
        Product(name: "Семена льна", category: "Орехи, семена, сухофрукты", proteins: 18.3, fats: 42.2, carbohydrates: 1.6, calories: 534),
        Product(name: "Семена мака", category: "Орехи, семена, сухофрукты", proteins: 17.5, fats: 47.5, carbohydrates: 14.5, calories: 556),
        Product(name: "Семена чиа", category: "Орехи, семена, сухофрукты", proteins: 16.5, fats: 30.7, carbohydrates: 7.7, calories: 486),
        Product(name: "Фисташки сырые", category: "Орехи, семена, сухофрукты", proteins: 20.2, fats: 45.3, carbohydrates: 16.6, calories: 560),
        Product(name: "Фисташки жареные без масла с добавлением соли", category: "Орехи, семена, сухофрукты", proteins: 21.1, fats: 45.8, carbohydrates: 17.3, calories: 569),
        Product(name: "Фундук (лещина окультуренная)", category: "Орехи, семена, сухофрукты", proteins: 15, fats: 61.5, carbohydrates: 9.4, calories: 651),
        Product(name: "Фундук жареный", category: "Орехи, семена, сухофрукты", proteins: 17.8, fats: 66.1, carbohydrates: 9.4, calories: 703),
        Product(name: "Бананы сушеные", category: "Орехи, семена, сухофрукты", proteins: 3.9, fats: 1.8, carbohydrates: 78.4, calories: 346),
        Product(name: "Вишня сушеная", category: "Орехи, семена, сухофрукты", proteins: 1.5, fats: 0, carbohydrates: 73, calories: 290),
        Product(name: "Груша сушеная", category: "Орехи, семена, сухофрукты", proteins: 2.3, fats: 0.6, carbohydrates: 62.6, calories: 270),
        Product(name: "Дыня сушеная", category: "Орехи, семена, сухофрукты", proteins: 0.7, fats: 0.1, carbohydrates: 82.2, calories: 341),
        Product(name: "Изюм", category: "Орехи, семена, сухофрукты", proteins: 2.5, fats: 0.54, carbohydrates: 67.7, calories: 296),
        Product(name: "Изюм кишмиш", category: "Орехи, семена, сухофрукты", proteins: 2.3, fats: 0.5, carbohydrates: 65.8, calories: 281),
        Product(name: "Инжир сушеный", category: "Орехи, семена, сухофрукты", proteins: 3.1, fats: 0.8, carbohydrates: 57.9, calories: 257),
        Product(name: "Курага", category: "Орехи, семена, сухофрукты", proteins: 5.2, fats: 0.3, carbohydrates: 51, calories: 232),
        Product(name: "Персик сушеный", category: "Орехи, семена, сухофрукты", proteins: 3, fats: 0.4, carbohydrates: 57.7, calories: 254),
        Product(name: "Урюк", category: "Орехи, семена, сухофрукты", proteins: 5, fats: 0.4, carbohydrates: 53, calories: 242),
        Product(name: "Финики", category: "Орехи, семена, сухофрукты", proteins: 2.5, fats: 0.5, carbohydrates: 69.2, calories: 292),
        Product(name: "Чернослив (слива сушеная)", category: "Орехи, семена, сухофрукты", proteins: 2.3, fats: 0.7, carbohydrates: 57.5, calories: 256),
        Product(name: "Яблоки сушеные", category: "Орехи, семена, сухофрукты", proteins: 2.2, fats: 0.1, carbohydrates: 59, calories: 253)
    ],
    "Сахар, сладкое и кондитерские изделия": [
        Product(name: "Сахар-песок", category: "Сахар, сладкое и кондитерские изделия", proteins: 0.0, fats: 0.0, carbohydrates: 99.8, calories: 399),
        Product(name: "Сахар-рафинад", category: "Сахар, сладкое и кондитерские изделия", proteins: 0.0, fats: 0.0, carbohydrates: 99.9, calories: 400),
        Product(name: "Сахар тростниковый", category: "Сахар, сладкое и кондитерские изделия", proteins: 0.0, fats: 0.0, carbohydrates: 99.7, calories: 394),
        Product(name: "Варенье вишневое", category: "Сахар, сладкое и кондитерские изделия", proteins: 0.0, fats: 0.0, carbohydrates: 64.0, calories: 256),
        Product(name: "Варенье клубничное", category: "Сахар, сладкое и кондитерские изделия", proteins: 0.3, fats: 0.0, carbohydrates: 74.0, calories: 282),
        Product(name: "Варенье малиновое", category: "Сахар, сладкое и кондитерские изделия", proteins: 0.6, fats: 0.0, carbohydrates: 70.4, calories: 270),
        Product(name: "Варенье сливовое", category: "Сахар, сладкое и кондитерские изделия", proteins: 0.7, fats: 0.0, carbohydrates: 74.6, calories: 283),
        Product(name: "Варенье черничное", category: "Сахар, сладкое и кондитерские изделия", proteins: 0.4, fats: 0.0, carbohydrates: 51.6, calories: 211),
        Product(name: "Варенье из черной смородины", category: "Сахар, сладкое и кондитерские изделия", proteins: 0.6, fats: 0.0, carbohydrates: 72.9, calories: 282),
        Product(name: "Варенье яблочное", category: "Сахар, сладкое и кондитерские изделия", proteins: 0.4, fats: 0.0, carbohydrates: 68.7, calories: 260),
        Product(name: "Вафли", category: "Сахар, сладкое и кондитерские изделия", proteins: 3.2, fats: 2.8, carbohydrates: 52.0, calories: 342),
        Product(name: "Галеты", category: "Сахар, сладкое и кондитерские изделия", proteins: 11.0, fats: 1.5, carbohydrates: 75.0, calories: 360),
        Product(name: "Зефир", category: "Сахар, сладкое и кондитерские изделия", proteins: 0.7, fats: 0.1, carbohydrates: 78.3, calories: 299),
        Product(name: "Зефир в шоколаде", category: "Сахар, сладкое и кондитерские изделия", proteins: 2.0, fats: 10.0, carbohydrates: 70.0, calories: 365),
        Product(name: "Какао-порошок", category: "Сахар, сладкое и кондитерские изделия", proteins: 24.3, fats: 15.0, carbohydrates: 10.2, calories: 289),
        Product(name: "Карамель", category: "Сахар, сладкое и кондитерские изделия", proteins: 0.0, fats: 1.0, carbohydrates: 91.2, calories: 371),
        Product(name: "Кекс с изюмом", category: "Сахар, сладкое и кондитерские изделия", proteins: 6.4, fats: 17.6, carbohydrates: 53.6, calories: 384),
        Product(name: "Козинак из семян подсолнечника", category: "Сахар, сладкое и кондитерские изделия", proteins: 14.8, fats: 42.6, carbohydrates: 34.5, calories: 576),
        Product(name: "Конфеты \"Белочка\"", category: "Сахар, сладкое и кондитерские изделия", proteins: 8.8, fats: 33.1, carbohydrates: 53.4, calories: 538),
        Product(name: "Конфеты \"Коровка\"", category: "Сахар, сладкое и кондитерские изделия", proteins: 2.7, fats: 4.4, carbohydrates: 82.4, calories: 351),
        Product(name: "Крахмал картофельный", category: "Сахар, сладкое и кондитерские изделия", proteins: 0.1, fats: 0.0, carbohydrates: 79.6, calories: 299),
        Product(name: "Круассаны", category: "Сахар, сладкое и кондитерские изделия", proteins: 5.5, fats: 19.7, carbohydrates: 42.0, calories: 380),
        Product(name: "Мармелад", category: "Сахар, сладкое и кондитерские изделия", proteins: 0.0, fats: 0.1, carbohydrates: 77.7, calories: 296),
        Product(name: "Мед натуральный", category: "Сахар, сладкое и кондитерские изделия", proteins: 0.8, fats: 0.0, carbohydrates: 80.3, calories: 308),
        Product(name: "Молоко сгущенное с сахаром 8,5%, Беларусь", category: "Сахар, сладкое и кондитерские изделия", proteins: 7.2, fats: 8.5, carbohydrates: 56.0, calories: 329),
        Product(name: "Мороженое молочное", category: "Сахар, сладкое и кондитерские изделия", proteins: 3.2, fats: 3.5, carbohydrates: 21.3, calories: 126),
        Product(name: "Мороженое пломбир", category: "Сахар, сладкое и кондитерские изделия", proteins: 3.2, fats: 15.0, carbohydrates: 20.8, calories: 227),
        Product(name: "Нуга", category: "Сахар, сладкое и кондитерские изделия", proteins: 6.0, fats: 11.0, carbohydrates: 60.0, calories: 405),
        Product(name: "Пастила", category: "Сахар, сладкое и кондитерские изделия", proteins: 0.5, fats: 0.0, carbohydrates: 80.4, calories: 305),
        Product(name: "Печенье", category: "Сахар, сладкое и кондитерские изделия", proteins: 7.4, fats: 5.2, carbohydrates: 75.0, calories: 376),
        Product(name: "Печенье овсяное", category: "Сахар, сладкое и кондитерские изделия", proteins: 6.5, fats: 14.4, carbohydrates: 71.8, calories: 437),
        Product(name: "Пирожные", category: "Сахар, сладкое и кондитерские изделия", proteins: 1.0, fats: 9.2, carbohydrates: 42.0, calories: 370),
        Product(name: "Повидло", category: "Сахар, сладкое и кондитерские изделия", proteins: 0.1, fats: 0.1, carbohydrates: 57.0, calories: 215),
        Product(name: "Пряники Тульские", category: "Сахар, сладкое и кондитерские изделия", proteins: 5.5, fats: 6.5, carbohydrates: 68.0, calories: 360),
        Product(name: "Рахат-лукум", category: "Сахар, сладкое и кондитерские изделия", proteins: 0.0, fats: 0.7, carbohydrates: 79.0, calories: 310),
        Product(name: "Торт медовый", category: "Сахар, сладкое и кондитерские изделия", proteins: 5.4, fats: 26.0, carbohydrates: 42.0, calories: 430),
        Product(name: "Торт \"Наполеон\"", category: "Сахар, сладкое и кондитерские изделия", proteins: 5.9, fats: 33.0, carbohydrates: 23.0, calories: 410),
        Product(name: "Торт \"Полет\"", category: "Сахар, сладкое и кондитерские изделия", proteins: 5.7, fats: 24.8, carbohydrates: 55.4, calories: 456),
        Product(name: "Торт \"Прага\"", category: "Сахар, сладкое и кондитерские изделия", proteins: 4.6, fats: 24.0, carbohydrates: 42.0, calories: 410),
        Product(name: "Торт \"Сказка\"", category: "Сахар, сладкое и кондитерские изделия", proteins: 4.3, fats: 17.1, carbohydrates: 46.9, calories: 351),
        Product(name: "Торт сметанно-ореховый", category: "Сахар, сладкое и кондитерские изделия", proteins: 2.9, fats: 13.5, carbohydrates: 35.3, calories: 275),
        Product(name: "Халва подсолнечная", category: "Сахар, сладкое и кондитерские изделия", proteins: 11.6, fats: 29.7, carbohydrates: 54.0, calories: 516),
        Product(name: "Чак-чак", category: "Сахар, сладкое и кондитерские изделия", proteins: 8.6, fats: 1.9, carbohydrates: 77.9, calories: 363),
        Product(name: "Шоколадный батончик \"Сникерс\"", category: "Сахар, сладкое и кондитерские изделия", proteins: 9.3, fats: 27.9, carbohydrates: 54.6, calories: 507),
        Product(name: "Шоколад горький", category: "Сахар, сладкое и кондитерские изделия", proteins: 8.0, fats: 36.0, carbohydrates: 46.8, calories: 540),
        Product(name: "Шоколад молочный", category: "Сахар, сладкое и кондитерские изделия", proteins: 6.9, fats: 35.7, carbohydrates: 54.4, calories: 550)
    ],
    "Соки, напитки безалкогольные": [
        Product(name: "Абрикосовый сок", category: "Соки, напитки безалкогольные", proteins: 0.5, fats: 0.0, carbohydrates: 9.0, calories: 38),
        Product(name: "Ананасовый сок", category: "Соки, напитки безалкогольные", proteins: 0.3, fats: 0.1, carbohydrates: 11.4, calories: 48),
        Product(name: "Апельсиновый сок", category: "Соки, напитки безалкогольные", proteins: 0.7, fats: 0.1, carbohydrates: 8.1, calories: 36),
        Product(name: "Березовый сок", category: "Соки, напитки безалкогольные", proteins: 0.1, fats: 0.0, carbohydrates: 5.8, calories: 24),
        Product(name: "Виноградный сок", category: "Соки, напитки безалкогольные", proteins: 0.3, fats: 0.0, carbohydrates: 14.0, calories: 54),
        Product(name: "Гранатовый сок", category: "Соки, напитки безалкогольные", proteins: 0.3, fats: 0.1, carbohydrates: 14.2, calories: 56),
        Product(name: "Грейпфрутовый сок", category: "Соки, напитки безалкогольные", proteins: 0.3, fats: 0.1, carbohydrates: 6.5, calories: 29),
        Product(name: "Грушевый сок", category: "Соки, напитки безалкогольные", proteins: 0.4, fats: 0.0, carbohydrates: 11.0, calories: 45),
        Product(name: "Лаймовый сок, свежевыжатый", category: "Соки, напитки безалкогольные", proteins: 0.4, fats: 0.1, carbohydrates: 8.0, calories: 25),
        Product(name: "Лимонный сок, свежевыжатый", category: "Соки, напитки безалкогольные", proteins: 0.35, fats: 0.24, carbohydrates: 6.6, calories: 22),
        Product(name: "Манго сок", category: "Соки, напитки безалкогольные", proteins: 0.0, fats: 0.0, carbohydrates: 13.5, calories: 54),
        Product(name: "Мандариновый сок", category: "Соки, напитки безалкогольные", proteins: 0.8, fats: 0.0, carbohydrates: 8.1, calories: 35),
        Product(name: "Морковный сок", category: "Соки, напитки безалкогольные", proteins: 1.1, fats: 0.1, carbohydrates: 6.4, calories: 33),
        Product(name: "Персиковый сок", category: "Соки, напитки безалкогольные", proteins: 0.3, fats: 0.0, carbohydrates: 9.5, calories: 39),
        Product(name: "Томатный сок", category: "Соки, напитки безалкогольные", proteins: 1.0, fats: 0.1, carbohydrates: 2.9, calories: 18),
        Product(name: "Тыквенный сок", category: "Соки, напитки безалкогольные", proteins: 0.0, fats: 0.0, carbohydrates: 9.0, calories: 38),
        Product(name: "Яблочный сок", category: "Соки, напитки безалкогольные", proteins: 0.4, fats: 0.1, carbohydrates: 9.8, calories: 42),
        Product(name: "7up", category: "Соки, напитки безалкогольные", proteins: 0.0, fats: 0.0, carbohydrates: 8.7, calories: 38),
        Product(name: "Квас \"Очаковский\"", category: "Соки, напитки безалкогольные", proteins: 0.0, fats: 0.0, carbohydrates: 5.5, calories: 30),
        Product(name: "Квас хлебный", category: "Соки, напитки безалкогольные", proteins: 0.2, fats: 0.0, carbohydrates: 5.2, calories: 27),
        Product(name: "Кока-кола", category: "Соки, напитки безалкогольные", proteins: 0.0, fats: 0.0, carbohydrates: 10.4, calories: 42),
        Product(name: "Кофе черный зерновой без сахара", category: "Соки, напитки безалкогольные", proteins: 0.2, fats: 0.5, carbohydrates: 0.3, calories: 7),
        Product(name: "Кофе с молоком и сахаром", category: "Соки, напитки безалкогольные", proteins: 0.7, fats: 1.0, carbohydrates: 11.2, calories: 58),
        Product(name: "Лимонад", category: "Соки, напитки безалкогольные", proteins: 0.0, fats: 0.0, carbohydrates: 6.4, calories: 26),
        Product(name: "Пепси", category: "Соки, напитки безалкогольные", proteins: 0.0, fats: 0.0, carbohydrates: 8.7, calories: 38),
        Product(name: "Пиво безалкогольное", category: "Соки, напитки безалкогольные", proteins: 0.0, fats: 0.0, carbohydrates: 4.1, calories: 22),
        Product(name: "Тоник", category: "Соки, напитки безалкогольные", proteins: 0.0, fats: 0.0, carbohydrates: 8.3, calories: 34),
        Product(name: "Фанта", category: "Соки, напитки безалкогольные", proteins: 0.0, fats: 0.0, carbohydrates: 11.7, calories: 48),
        Product(name: "Цикорий растворимый", category: "Соки, напитки безалкогольные", proteins: 0.1, fats: 0.0, carbohydrates: 2.8, calories: 11),
        Product(name: "Чай зеленый", category: "Соки, напитки безалкогольные", proteins: 0.0, fats: 0.0, carbohydrates: 0.0, calories: 0),
        Product(name: "Чай черный без сахара", category: "Соки, напитки безалкогольные", proteins: 0.1, fats: 0.0, carbohydrates: 0.0, calories: 0),
        Product(name: "Чай черный с сахаром", category: "Соки, напитки безалкогольные", proteins: 0.1, fats: 0.0, carbohydrates: 7.0, calories: 28),
        Product(name: "Чай черный с молоком и сахаром", category: "Соки, напитки безалкогольные", proteins: 0.7, fats: 0.8, carbohydrates: 8.2, calories: 43)
    ],
    "Напитки алкогольные": [
        Product(name: "Вермут Cinzano, Martini", category: "Напитки алкогольные", proteins: 0, fats: 0, carbohydrates: 14.5, calories: 138),
        Product(name: "Вина виноградные сухие белые и красные, в. т. ч. игристые", category: "Напитки алкогольные", proteins: 0.2, fats: 0, carbohydrates: 0.4, calories: 95),
        Product(name: "Вина виноградные полусухие белые и красные, в. т. ч. игристые", category: "Напитки алкогольные", proteins: 0.3, fats: 0, carbohydrates: 2.5, calories: 78),
        Product(name: "Вина виноградные полусладкие белые и красные, в. т. ч. игристые", category: "Напитки алкогольные", proteins: 0.2, fats: 0, carbohydrates: 5, calories: 88),
        Product(name: "Вина виноградные сладкие белые и красные, в. т. ч. игристые", category: "Напитки алкогольные", proteins: 0.2, fats: 0, carbohydrates: 8, calories: 100),
        Product(name: "Вина виноградные крепкие", category: "Напитки алкогольные", proteins: 0.4, fats: 0, carbohydrates: 12, calories: 163),
        Product(name: "Вина виноградные ликерные", category: "Напитки алкогольные", proteins: 0.5, fats: 0, carbohydrates: 30, calories: 212),
        Product(name: "Виски", category: "Напитки алкогольные", proteins: 0, fats: 0, carbohydrates: 0.4, calories: 235),
        Product(name: "Водка", category: "Напитки алкогольные", proteins: 0, fats: 0, carbohydrates: 0.4, calories: 235),
        Product(name: "Джин", category: "Напитки алкогольные", proteins: 0, fats: 0, carbohydrates: 0, calories: 230),
        Product(name: "Джин-тоник", category: "Напитки алкогольные", proteins: 0, fats: 0, carbohydrates: 6.7, calories: 78),
        Product(name: "Кагор", category: "Напитки алкогольные", proteins: 0, fats: 0, carbohydrates: 16, calories: 147),
        Product(name: "Коньяк", category: "Напитки алкогольные", proteins: 0, fats: 0, carbohydrates: 0.1, calories: 239),
        Product(name: "Ликер Amaretto", category: "Напитки алкогольные", proteins: 0, fats: 0, carbohydrates: 35, calories: 280),
        Product(name: "Ликер Baileys", category: "Напитки алкогольные", proteins: 3, fats: 13, carbohydrates: 25, calories: 327),
        Product(name: "Ликер \"Куантро\"", category: "Напитки алкогольные", proteins: 0, fats: 0, carbohydrates: 20, calories: 197),
        Product(name: "Ликер \"Калуа\"", category: "Напитки алкогольные", proteins: 0.6, fats: 0.7, carbohydrates: 41.7, calories: 291),
        Product(name: "Ликер \"Малибу\"", category: "Напитки алкогольные", proteins: 0, fats: 0, carbohydrates: 20, calories: 197),
        Product(name: "Пиво светлое легкое", category: "Напитки алкогольные", proteins: 0.3, fats: 0, carbohydrates: 5.5, calories: 46),
        Product(name: "Пиво темное легкое", category: "Напитки алкогольные", proteins: 0.3, fats: 0, carbohydrates: 5.7, calories: 48),
        Product(name: "Портвейн", category: "Напитки алкогольные", proteins: 0.4, fats: 0, carbohydrates: 12, calories: 163),
        Product(name: "Ром", category: "Напитки алкогольные", proteins: 0, fats: 0, carbohydrates: 0, calories: 220),
        Product(name: "Саке", category: "Напитки алкогольные", proteins: 0.5, fats: 0, carbohydrates: 5, calories: 134),
        Product(name: "Самогон", category: "Напитки алкогольные", proteins: 0.1, fats: 0.1, carbohydrates: 0.4, calories: 235),
        Product(name: "Спирт этиловый 96%", category: "Напитки алкогольные", proteins: 4, fats: 0, carbohydrates: 3.8, calories: 710),
        Product(name: "Текила", category: "Напитки алкогольные", proteins: 1.4, fats: 0.3, carbohydrates: 24, calories: 231),
        Product(name: "Чача", category: "Напитки алкогольные", proteins: 0.1, fats: 0.1, carbohydrates: 0.5, calories: 225)
    ]
]
