//
//  Product.swift
//  FitnessPad
//
//  Created by Марк Кулик on 29.01.2025.
//

import Foundation


struct Category: Hashable {
    let name: String
    let categoryImage: String
}


struct ProductItem: Identifiable {
    let id = UUID()
    let name: String
    let category: Category
    let proteins: Double
    let fats: Double
    let carbohydrates: Double
    let calories: Double
}

// Теперь категории можно определять отдельно
let categories = [
    Category(name: "Хлебобулочные изделия", categoryImage: "bread"),
    Category(name: "Макароны, крупы", categoryImage: "pasta"),
    Category(name: "Молочные продукты", categoryImage: "milk"),
    Category(name: "Мясо и птица", categoryImage: "meat_chicken"),
    Category(name: "Колбасы, сосиски", categoryImage: "sausagies"),
    Category(name: "Рыба и морепродукты", categoryImage: "fish"),
    Category(name: "Консервы рыбные", categoryImage: "seafood_can"),
    Category(name: "Яйцепродукты", categoryImage: "egg"),
    Category(name: "Масла и жировые продукты", categoryImage: "butter"),
    Category(name: "Овощи, зелень, грибы", categoryImage: "veg_mush"),
    Category(name: "Консервы овощные", categoryImage: "veg_can"),
    Category(name: "Фрукты, ягоды", categoryImage: "fruit"),
    Category(name: "Орехи и сухофрукты", categoryImage: "nut"),
    Category(name: "Сладкие изделия", categoryImage: "sweet"),
    Category(name: "Напитки безалкогольные", categoryImage: "non_alcohol"),
    Category(name: "Напитки алкогольные", categoryImage: "alcohol")
]

let productsByCategory: [Category: [ProductItem]] = [
    categories[0]: [
            ProductItem(name: "product_wheat_bread_premium".localized, category: categories[0], proteins: 7.5, fats: 0.8, carbohydrates: 49.2, calories: 235),
            ProductItem(name: "product_wheat_bread_first_grade".localized, category: categories[0], proteins: 7.6, fats: 0.9, carbohydrates: 49.7, calories: 226),
            ProductItem(name: "product_rye_wheat_bread".localized, category: categories[0], proteins: 6.8, fats: 1.2, carbohydrates: 46.4, calories: 215),
            ProductItem(name: "product_rye_bread".localized, category: categories[0], proteins: 4.7, fats: 0.7, carbohydrates: 49.8, calories: 214),
            ProductItem(name: "product_borodinsky_bread".localized, category: categories[0], proteins: 6.9, fats: 1.3, carbohydrates: 40.9, calories: 208),
            ProductItem(name: "product_grain_bread".localized, category: categories[0], proteins: 8.6, fats: 1.4, carbohydrates: 45.1, calories: 228),
            ProductItem(name: "product_whole_grain_bread".localized, category: categories[0], proteins: 13.3, fats: 4.2, carbohydrates: 43.3, calories: 265),
            ProductItem(name: "product_dr_korner_seven_grains_crisps".localized, category: categories[0], proteins: 10, fats: 2, carbohydrates: 57, calories: 290),
            ProductItem(name: "product_dr_korner_borodinsky_crisps".localized, category: categories[0], proteins: 11, fats: 3, carbohydrates: 52, calories: 280),
            ProductItem(name: "product_dr_korner_buckwheat_crisps".localized, category: categories[0], proteins: 11.6, fats: 3, carbohydrates: 52.4, calories: 283),
            ProductItem(name: "product_dr_korner_rice_crisps".localized, category: categories[0], proteins: 6, fats: 1, carbohydrates: 69, calories: 310),
            ProductItem(name: "product_pastries".localized, category: categories[0], proteins: 7.4, fats: 2.2, carbohydrates: 52.9, calories: 269),
            ProductItem(name: "product_wheat_flour_rusks".localized, category: categories[0], proteins: 11.2, fats: 1.4, carbohydrates: 72.4, calories: 331)
        ],
    categories[1]: [
            ProductItem(name: "product_pasta_durum_wheat_premium".localized, category: categories[1], proteins: 11, fats: 1.3, carbohydrates: 70.5, calories: 338),
            ProductItem(name: "product_pasta_durum_wheat_premium_cooked".localized, category: categories[1], proteins: 3.6, fats: 0.4, carbohydrates: 20, calories: 98),
            ProductItem(name: "product_pasta_premium".localized, category: categories[1], proteins: 10.4, fats: 1.1, carbohydrates: 69.7, calories: 337),
            ProductItem(name: "product_pasta_premium_cooked".localized, category: categories[1], proteins: 3.5, fats: 0.4, carbohydrates: 23.2, calories: 112),
            ProductItem(name: "product_buckwheat_kernel".localized, category: categories[1], proteins: 12.6, fats: 3.3, carbohydrates: 57.1, calories: 308),
            ProductItem(name: "product_buckwheat_cooked".localized, category: categories[1], proteins: 4.1, fats: 1, carbohydrates: 18.5, calories: 100),
            ProductItem(name: "product_buckwheat_prodel".localized, category: categories[1], proteins: 9.5, fats: 2.3, carbohydrates: 60.4, calories: 300),
            ProductItem(name: "product_buckwheat_green_mistral".localized, category: categories[1], proteins: 13.4, fats: 3, carbohydrates: 68, calories: 328),
            ProductItem(name: "product_rice_white_polished".localized, category: categories[1], proteins: 7, fats: 1, carbohydrates: 74, calories: 333),
            ProductItem(name: "product_rice_white_polished_cooked".localized, category: categories[1], proteins: 2.3, fats: 0.2, carbohydrates: 28.7, calories: 130),
            ProductItem(name: "product_rice_long_grain_unpolished".localized, category: categories[1], proteins: 7.5, fats: 2, carbohydrates: 73, calories: 340),
            ProductItem(name: "product_rice_unpolished_cooked".localized, category: categories[1], proteins: 2.5, fats: 0.9, carbohydrates: 23, calories: 112),
            ProductItem(name: "product_rice_red_unpolished".localized, category: categories[1], proteins: 7.5, fats: 3, carbohydrates: 68, calories: 330),
            ProductItem(name: "product_rice_wild_black".localized, category: categories[1], proteins: 14.7, fats: 1.1, carbohydrates: 68.7, calories: 357),
            ProductItem(name: "product_rice_wild_black_cooked".localized, category: categories[1], proteins: 4, fats: 0.3, carbohydrates: 19.5, calories: 101),
            ProductItem(name: "product_millet".localized, category: categories[1], proteins: 11.5, fats: 3.3, carbohydrates: 66.5, calories: 342),
            ProductItem(name: "product_millet_cooked".localized, category: categories[1], proteins: 3.5, fats: 1.1, carbohydrates: 23.6, calories: 119),
            ProductItem(name: "product_oat_groat".localized, category: categories[1], proteins: 12.3, fats: 6.1, carbohydrates: 59.5, calories: 342),
            ProductItem(name: "product_oat_flakes".localized, category: categories[1], proteins: 12.3, fats: 6.2, carbohydrates: 61.8, calories: 352),
            ProductItem(name: "product_oat_flakes_porridge_water".localized, category: categories[1], proteins: 3, fats: 1.7, carbohydrates: 15, calories: 88),
            ProductItem(name: "product_oat_flakes_porridge_milk".localized, category: categories[1], proteins: 3.2, fats: 4.1, carbohydrates: 14.2, calories: 102),
            ProductItem(name: "product_oat_tolokno".localized, category: categories[1], proteins: 12.5, fats: 6, carbohydrates: 64.9, calories: 363),
            ProductItem(name: "product_barley_pearl".localized, category: categories[1], proteins: 9.3, fats: 1.1, carbohydrates: 66.9, calories: 315),
            ProductItem(name: "product_barley_pearl_cooked".localized, category: categories[1], proteins: 3.1, fats: 0.4, carbohydrates: 22.2, calories: 109),
            ProductItem(name: "product_barley_groat".localized, category: categories[1], proteins: 10, fats: 1.3, carbohydrates: 65.4, calories: 313),
            ProductItem(name: "product_barley_groat_cooked".localized, category: categories[1], proteins: 2.3, fats: 0.3, carbohydrates: 15.7, calories: 76),
            ProductItem(name: "product_wheat_groat_poltavskaya".localized, category: categories[1], proteins: 11.5, fats: 1.3, carbohydrates: 67.9, calories: 329),
            ProductItem(name: "product_wheat_groat_poltavskaya_cooked".localized, category: categories[1], proteins: 2.5, fats: 0.3, carbohydrates: 14.5, calories: 71),
            ProductItem(name: "product_corn_grain".localized, category: categories[1], proteins: 10.3, fats: 4.9, carbohydrates: 60, calories: 325),
            ProductItem(name: "product_corn_groat".localized, category: categories[1], proteins: 8.3, fats: 1.2, carbohydrates: 71, calories: 328),
            ProductItem(name: "product_semolina".localized, category: categories[1], proteins: 10.3, fats: 1, carbohydrates: 70.6, calories: 333),
            ProductItem(name: "product_semolina_porridge_water".localized, category: categories[1], proteins: 2.5, fats: 0.2, carbohydrates: 16.8, calories: 80),
            ProductItem(name: "product_semolina_porridge_milk".localized, category: categories[1], proteins: 3, fats: 3.2, carbohydrates: 15.3, calories: 98),
            // Бобовые
            ProductItem(name: "product_peas_grain".localized, category: categories[1], proteins: 20.5, fats: 2, carbohydrates: 49.5, calories: 298),
            ProductItem(name: "product_peas_whole_polished".localized, category: categories[1], proteins: 22, fats: 2, carbohydrates: 57, calories: 330),
            ProductItem(name: "product_peas_split".localized, category: categories[1], proteins: 23, fats: 1.6, carbohydrates: 48.1, calories: 299),
            ProductItem(name: "product_peas_cooked".localized, category: categories[1], proteins: 8.3, fats: 0.4, carbohydrates: 21, calories: 118),
            ProductItem(name: "product_green_peas_fresh".localized, category: categories[1], proteins: 5, fats: 0.2, carbohydrates: 8.3, calories: 55),
            ProductItem(name: "product_mung_bean".localized, category: categories[1], proteins: 23.9, fats: 1.2, carbohydrates: 62.6, calories: 347),
            ProductItem(name: "product_mung_bean_cooked".localized, category: categories[1], proteins: 7, fats: 0.4, carbohydrates: 19.2, calories: 105),
            ProductItem(name: "product_chickpeas".localized, category: categories[1], proteins: 20.5, fats: 4.3, carbohydrates: 63, calories: 360),
            ProductItem(name: "product_chickpeas_cooked".localized, category: categories[1], proteins: 8.9, fats: 2.6, carbohydrates: 27.4, calories: 164),
            ProductItem(name: "product_soybean_grain".localized, category: categories[1], proteins: 36.7, fats: 17.8, carbohydrates: 17.3, calories: 364),
            ProductItem(name: "product_soybean_beans".localized, category: categories[1], proteins: 36.4, fats: 19.9, carbohydrates: 30.1, calories: 446),
            ProductItem(name: "product_soybean_beans_cooked".localized, category: categories[1], proteins: 16.6, fats: 8.9, carbohydrates: 9.9, calories: 173),
            ProductItem(name: "product_red_beans_common".localized, category: categories[1], proteins: 23.5, fats: 0.8, carbohydrates: 60, calories: 333),
            ProductItem(name: "product_red_beans_cooked".localized, category: categories[1], proteins: 8.7, fats: 0.5, carbohydrates: 22.8, calories: 127),
            ProductItem(name: "product_green_beans".localized, category: categories[1], proteins: 2.5, fats: 0.3, carbohydrates: 3, calories: 23),
            ProductItem(name: "product_lentils".localized, category: categories[1], proteins: 24.6, fats: 1.1, carbohydrates: 63.4, calories: 352),
            ProductItem(name: "product_lentils_cooked".localized, category: categories[1], proteins: 9, fats: 0.4, carbohydrates: 20.1, calories: 116),
            ProductItem(name: "product_red_lentils".localized, category: categories[1], proteins: 21.6, fats: 1.1, carbohydrates: 48, calories: 314),
            ProductItem(name: "product_red_lentils_split_persian_mistral".localized, category: categories[1], proteins: 24.7, fats: 1.2, carbohydrates: 62.5, calories: 328),
            ProductItem(name: "product_amaranth_grain".localized, category: categories[1], proteins: 13.6, fats: 7, carbohydrates: 58.6, calories: 371),
            ProductItem(name: "product_amaranth_cooked".localized, category: categories[1], proteins: 3.8, fats: 1.6, carbohydrates: 16.6, calories: 102),
            ProductItem(name: "product_quinoa_grain".localized, category: categories[1], proteins: 14.1, fats: 6.1, carbohydrates: 57.2, calories: 368),
            ProductItem(name: "product_quinoa_cooked".localized, category: categories[1], proteins: 4.4, fats: 1.9, carbohydrates: 18.5, calories: 120)
        ],
    categories[2]: [
            ProductItem(name: "product_skim_milk".localized, category: categories[2], proteins: 3, fats: 0.05, carbohydrates: 4.9, calories: 32),
            ProductItem(name: "product_milk_1_5_fat".localized, category: categories[2], proteins: 3, fats: 1.5, carbohydrates: 4.8, calories: 45),
            ProductItem(name: "product_milk_2_5_fat".localized, category: categories[2], proteins: 2.9, fats: 2.5, carbohydrates: 4.8, calories: 54),
            ProductItem(name: "product_milk_3_2_fat".localized, category: categories[2], proteins: 2.9, fats: 3.2, carbohydrates: 4.7, calories: 60),
            ProductItem(name: "product_cream_10_fat".localized, category: categories[2], proteins: 2.7, fats: 10, carbohydrates: 4.4, calories: 119),
            ProductItem(name: "product_cream_20_fat".localized, category: categories[2], proteins: 2.5, fats: 20, carbohydrates: 4, calories: 205),
            ProductItem(name: "product_low_fat_cottage_cheese".localized, category: categories[2], proteins: 22, fats: 0.6, carbohydrates: 3.3, calories: 110),
            ProductItem(name: "product_cottage_cheese_5_fat".localized, category: categories[2], proteins: 21, fats: 5, carbohydrates: 3, calories: 145),
            ProductItem(name: "product_cottage_cheese_9_fat".localized, category: categories[2], proteins: 18, fats: 9, carbohydrates: 3, calories: 169),
            ProductItem(name: "product_cottage_cheese_18_fat".localized, category: categories[2], proteins: 15, fats: 18, carbohydrates: 2.8, calories: 236),
            ProductItem(name: "product_sour_cream_10_fat".localized, category: categories[2], proteins: 2.7, fats: 10, carbohydrates: 3.9, calories: 119),
            ProductItem(name: "product_sour_cream_20_fat".localized, category: categories[2], proteins: 2.5, fats: 20, carbohydrates: 3.4, calories: 206),
            ProductItem(name: "product_sour_cream_30_fat".localized, category: categories[2], proteins: 2.3, fats: 30, carbohydrates: 3.1, calories: 293),
            ProductItem(name: "product_low_fat_kefir".localized, category: categories[2], proteins: 3, fats: 0.05, carbohydrates: 4, calories: 31),
            ProductItem(name: "product_kefir_1_fat".localized, category: categories[2], proteins: 3, fats: 1, carbohydrates: 4, calories: 40),
            ProductItem(name: "product_kefir_2_5_fat".localized, category: categories[2], proteins: 2.9, fats: 2.5, carbohydrates: 4, calories: 53),
            ProductItem(name: "product_kefir_3_2_fat".localized, category: categories[2], proteins: 2.9, fats: 3.2, carbohydrates: 4, calories: 59),
            ProductItem(name: "product_cow_milk_cheese".localized, category: categories[2], proteins: 22.1, fats: 19.2, carbohydrates: 0.4, calories: 262),
            ProductItem(name: "product_adyghe_cheese".localized, category: categories[2], proteins: 19.8, fats: 19.8, carbohydrates: 1.5, calories: 264),
            ProductItem(name: "product_gouda_cheese".localized, category: categories[2], proteins: 25, fats: 27, carbohydrates: 2, calories: 356),
            ProductItem(name: "product_dutch_block_cheese".localized, category: categories[2], proteins: 26, fats: 26.8, carbohydrates: 0, calories: 352),
            ProductItem(name: "product_dutch_round_cheese".localized, category: categories[2], proteins: 23.7, fats: 30.4, carbohydrates: 0, calories: 375),
            ProductItem(name: "product_lamber_cheese".localized, category: categories[2], proteins: 23.7, fats: 30.5, carbohydrates: 0, calories: 377),
            ProductItem(name: "product_lamber_cream_cheese".localized, category: categories[2], proteins: 23.7, fats: 32.5, carbohydrates: 0, calories: 395),
            ProductItem(name: "product_maasdam_cheese".localized, category: categories[2], proteins: 23.5, fats: 26, carbohydrates: 0, calories: 350),
            ProductItem(name: "product_mozzarella_whole_milk".localized, category: categories[2], proteins: 22.2, fats: 22.3, carbohydrates: 2.2, calories: 300),
            ProductItem(name: "product_parmesan_cheese".localized, category: categories[2], proteins: 37.8, fats: 27.3, carbohydrates: 3.4, calories: 415),
            ProductItem(name: "product_russian_cheese".localized, category: categories[2], proteins: 23.2, fats: 29.5, carbohydrates: 0, calories: 364),
            ProductItem(name: "product_ricotta_whole_milk".localized, category: categories[2], proteins: 11.3, fats: 13, carbohydrates: 3, calories: 174),
            ProductItem(name: "product_suluguni_cheese".localized, category: categories[2], proteins: 20.5, fats: 22, carbohydrates: 0.4, calories: 286),
            ProductItem(name: "product_tilsit_cheese".localized, category: categories[2], proteins: 24.4, fats: 26, carbohydrates: 1.9, calories: 340),
            ProductItem(name: "product_feta_cheese".localized, category: categories[2], proteins: 14.2, fats: 21.3, carbohydrates: 4, calories: 264),
            ProductItem(name: "product_edam_cheese".localized, category: categories[2], proteins: 25, fats: 27.8, carbohydrates: 1.4, calories: 357),
            ProductItem(name: "product_processed_cheese".localized, category: categories[2], proteins: 16.8, fats: 11.2, carbohydrates: 23.8, calories: 257),
            ProductItem(name: "product_viola_cheese".localized, category: categories[2], proteins: 11, fats: 28, carbohydrates: 2, calories: 305),
            ProductItem(name: "product_activia_yogurt".localized, category: categories[2], proteins: 3.8, fats: 2.9, carbohydrates: 14, calories: 97),
            ProductItem(name: "product_greek_yogurt".localized, category: categories[2], proteins: 5, fats: 3.2, carbohydrates: 3.5, calories: 66),
            ProductItem(name: "product_actimel".localized, category: categories[2], proteins: 2.7, fats: 1.5, carbohydrates: 10.5, calories: 71)
        ],
    categories[3]: [
        ProductItem(name: "product_beef_1st_grade".localized, category: categories[3], proteins: 18.6, fats: 16, carbohydrates: 0, calories: 218),
        ProductItem(name: "product_beef_2nd_grade".localized, category: categories[3], proteins: 20, fats: 9.8, carbohydrates: 0, calories: 168),
        ProductItem(name: "product_beef_tenderloin".localized, category: categories[3], proteins: 22.2, fats: 7.1, carbohydrates: 0, calories: 158),
        ProductItem(name: "product_veal_1st_grade".localized, category: categories[3], proteins: 19.7, fats: 2, carbohydrates: 0, calories: 97),
        ProductItem(name: "product_fatty_pork".localized, category: categories[3], proteins: 11.7, fats: 49.3, carbohydrates: 0, calories: 491),
        ProductItem(name: "product_lean_pork".localized, category: categories[3], proteins: 14.3, fats: 33.3, carbohydrates: 0, calories: 357),
        ProductItem(name: "product_pork_tenderloin".localized, category: categories[3], proteins: 19.4, fats: 7.1, carbohydrates: 0, calories: 142),
        ProductItem(name: "product_lamb_1st_grade".localized, category: categories[3], proteins: 15.6, fats: 16.3, carbohydrates: 0, calories: 209),
        ProductItem(name: "product_lamb_2nd_grade".localized, category: categories[3], proteins: 19.8, fats: 9.6, carbohydrates: 0, calories: 166),
        ProductItem(name: "product_horse_meat".localized, category: categories[3], proteins: 20.2, fats: 7, carbohydrates: 0, calories: 187),
        ProductItem(name: "product_beef_tongue".localized, category: categories[3], proteins: 16, fats: 12.1, carbohydrates: 2.2, calories: 173),
        ProductItem(name: "product_pork_tongue".localized, category: categories[3], proteins: 15.9, fats: 16, carbohydrates: 2.1, calories: 208),
        ProductItem(name: "product_beef_liver".localized, category: categories[3], proteins: 17.9, fats: 3.7, carbohydrates: 5.3, calories: 127),
        ProductItem(name: "product_pork_liver".localized, category: categories[3], proteins: 18.8, fats: 3.8, carbohydrates: 4.7, calories: 109),
        ProductItem(name: "product_rabbit".localized, category: categories[3], proteins: 21.2, fats: 11, carbohydrates: 0, calories: 183),
        ProductItem(name: "product_wild_boar".localized, category: categories[3], proteins: 21.5, fats: 3.3, carbohydrates: 0, calories: 122),
        ProductItem(name: "product_elk".localized, category: categories[3], proteins: 23, fats: 1.5, carbohydrates: 0, calories: 111),
        ProductItem(name: "product_venison".localized, category: categories[3], proteins: 19.5, fats: 8.5, carbohydrates: 0, calories: 155),
        // Продукты из категории 4
        ProductItem(name: "product_broiler_chicken_1st_grade".localized, category: categories[3], proteins: 18.7, fats: 16.1, carbohydrates: 0, calories: 220),
        ProductItem(name: "product_broiler_chicken_2nd_grade".localized, category: categories[3], proteins: 19.7, fats: 11.2, carbohydrates: 0, calories: 180),
        ProductItem(name: "product_chicken_1st_grade".localized, category: categories[3], proteins: 18.2, fats: 18.4, carbohydrates: 0, calories: 238),
        ProductItem(name: "product_chicken_2nd_grade".localized, category: categories[3], proteins: 21.2, fats: 8.2, carbohydrates: 0, calories: 159),
        ProductItem(name: "product_chicken_breast".localized, category: categories[3], proteins: 23.6, fats: 1.9, carbohydrates: 0, calories: 113),
        ProductItem(name: "product_chicken_drumsticks".localized, category: categories[3], proteins: 16.8, fats: 10.2, carbohydrates: 0, calories: 158),
        ProductItem(name: "product_chicken_liver".localized, category: categories[3], proteins: 19.1, fats: 6.3, carbohydrates: 0.6, calories: 136),
        ProductItem(name: "product_chicken_heart".localized, category: categories[3], proteins: 15.8, fats: 10.3, carbohydrates: 0.8, calories: 159),
        ProductItem(name: "product_turkey".localized, category: categories[3], proteins: 19.5, fats: 22, carbohydrates: 0, calories: 276),
        ProductItem(name: "product_turkey_breast".localized, category: categories[3], proteins: 23.6, fats: 1.5, carbohydrates: 0, calories: 114),
        ProductItem(name: "product_turkey_mince".localized, category: categories[3], proteins: 20, fats: 8, carbohydrates: 0.5, calories: 161),
        ProductItem(name: "product_duck_meat_and_skin".localized, category: categories[3], proteins: 15.8, fats: 38, carbohydrates: 0, calories: 405),
        ProductItem(name: "product_wild_duck_meat_and_skin".localized, category: categories[3], proteins: 17.4, fats: 15.2, carbohydrates: 0, calories: 211),
        ProductItem(name: "product_wild_duck_meat".localized, category: categories[3], proteins: 19.8, fats: 4.3, carbohydrates: 0, calories: 123),
        ProductItem(name: "product_quail_meat_and_skin".localized, category: categories[3], proteins: 19.6, fats: 12, carbohydrates: 0, calories: 192),
        ProductItem(name: "product_ostrich_meat".localized, category: categories[3], proteins: 21.8, fats: 2.3, carbohydrates: 0, calories: 114),
        ProductItem(name: "product_pheasant_meat_and_skin".localized, category: categories[3], proteins: 22.7, fats: 9.3, carbohydrates: 0, calories: 181),
        ProductItem(name: "product_pheasant_breast".localized, category: categories[3], proteins: 24.3, fats: 3.2, carbohydrates: 0, calories: 133)
    ],
    categories[4]: [
            ProductItem(name: "product_diet_sausage".localized, category: categories[4], proteins: 12.1, fats: 13.5, carbohydrates: 0, calories: 170),
            ProductItem(name: "product_doctor_sausage".localized, category: categories[4], proteins: 12.8, fats: 22.2, carbohydrates: 1.5, calories: 257),
            ProductItem(name: "product_amateur_sausage".localized, category: categories[4], proteins: 12.2, fats: 28, carbohydrates: 0.1, calories: 301),
            ProductItem(name: "product_milk_sausage".localized, category: categories[4], proteins: 11.7, fats: 22.8, carbohydrates: 0.2, calories: 252),
            ProductItem(name: "product_moscow_sausage".localized, category: categories[4], proteins: 11.5, fats: 21.8, carbohydrates: 2, calories: 250),
            ProductItem(name: "product_russian_sausage".localized, category: categories[4], proteins: 11.5, fats: 27.9, carbohydrates: 1.7, calories: 302),
            ProductItem(name: "product_smoked_moscow_sausage".localized, category: categories[4], proteins: 19.1, fats: 36.6, carbohydrates: 0.2, calories: 406),
            ProductItem(name: "product_servelat_sausage".localized, category: categories[4], proteins: 16.1, fats: 40.1, carbohydrates: 0, calories: 425),
            ProductItem(name: "product_krakow_sausage".localized, category: categories[4], proteins: 16.2, fats: 44.6, carbohydrates: 0, calories: 466),
            ProductItem(name: "product_odessa_sausage".localized, category: categories[4], proteins: 14.8, fats: 38.1, carbohydrates: 0.3, calories: 402),
            ProductItem(name: "product_braunschweig_sausage".localized, category: categories[4], proteins: 27.7, fats: 42.2, carbohydrates: 0.2, calories: 491),
            ProductItem(name: "product_smoked_moscow_sausage".localized, category: categories[4], proteins: 24.8, fats: 41.5, carbohydrates: 0, calories: 473),
            ProductItem(name: "product_pork_smoked_sausage".localized, category: categories[4], proteins: 13, fats: 57, carbohydrates: 0.2, calories: 566),
            ProductItem(name: "product_grain_smoked_sausage".localized, category: categories[4], proteins: 9.9, fats: 62.8, carbohydrates: 0.3, calories: 606),
            ProductItem(name: "product_liver_sausage".localized, category: categories[4], proteins: 14.4, fats: 28.5, carbohydrates: 2.2, calories: 326),
            ProductItem(name: "product_smoked_brisket".localized, category: categories[4], proteins: 8.9, fats: 63.3, carbohydrates: 0, calories: 605),
            ProductItem(name: "product_smoked_loin".localized, category: categories[4], proteins: 10.5, fats: 47.4, carbohydrates: 0, calories: 469),
            ProductItem(name: "product_chopped_ham".localized, category: categories[4], proteins: 16.3, fats: 20.7, carbohydrates: 1.8, calories: 263),
            ProductItem(name: "product_milk_sausages".localized, category: categories[4], proteins: 11, fats: 23.9, carbohydrates: 0.4, calories: 261),
            ProductItem(name: "product_beef_sausages".localized, category: categories[4], proteins: 10.4, fats: 20.1, carbohydrates: 0.8, calories: 226),
            ProductItem(name: "product_pork_sausages".localized, category: categories[4], proteins: 9.5, fats: 34.3, carbohydrates: 0, calories: 342),
            ProductItem(name: "product_chicken_sausages".localized, category: categories[4], proteins: 10.8, fats: 22.4, carbohydrates: 4.2, calories: 259),
            ProductItem(name: "product_beef_frankfurters".localized, category: categories[4], proteins: 11.4, fats: 18.2, carbohydrates: 1.3, calories: 215),
            ProductItem(name: "product_pork_frankfurters".localized, category: categories[4], proteins: 10.1, fats: 31.6, carbohydrates: 1.8, calories: 322),
            ProductItem(name: "product_shpikachki".localized, category: categories[4], proteins: 10, fats: 33, carbohydrates: 0, calories: 337),
            ProductItem(name: "product_canned_beef".localized, category: categories[4], proteins: 16.8, fats: 17, carbohydrates: 0.2, calories: 220),
            ProductItem(name: "product_canned_pork".localized, category: categories[4], proteins: 14.9, fats: 32.2, carbohydrates: 0.2, calories: 349)
        ],

    categories[5]: [
        ProductItem(name: "product_argentina_fish".localized, category: categories[5], proteins: 17.6, fats: 2, carbohydrates: 0, calories: 88),
        ProductItem(name: "product_white_amur".localized, category: categories[5], proteins: 18.6, fats: 5.3, carbohydrates: 0, calories: 134),
        ProductItem(name: "product_bullhead_fish".localized, category: categories[5], proteins: 17.5, fats: 2, carbohydrates: 0, calories: 88),
        ProductItem(name: "product_vobla_fish".localized, category: categories[5], proteins: 18, fats: 2.8, carbohydrates: 0, calories: 95),
        ProductItem(name: "product_pink_salmon".localized, category: categories[5], proteins: 20.5, fats: 6.5, carbohydrates: 0, calories: 140),
        ProductItem(name: "product_dorado_fish".localized, category: categories[5], proteins: 18, fats: 3, carbohydrates: 0, calories: 96),
        ProductItem(name: "product_spotted_wolffish".localized, category: categories[5], proteins: 19.6, fats: 5.3, carbohydrates: 0, calories: 126),
        ProductItem(name: "product_squid".localized, category: categories[5], proteins: 18, fats: 2.2, carbohydrates: 2, calories: 100),
        ProductItem(name: "product_far_east_flounder".localized, category: categories[5], proteins: 15.7, fats: 3, carbohydrates: 0, calories: 90),
        ProductItem(name: "product_crucian_carp".localized, category: categories[5], proteins: 17.7, fats: 1.8, carbohydrates: 0, calories: 87),
        ProductItem(name: "product_carp".localized, category: categories[5], proteins: 16, fats: 5.3, carbohydrates: 0, calories: 112),
        ProductItem(name: "product_chum_salmon".localized, category: categories[5], proteins: 19, fats: 5.6, carbohydrates: 0, calories: 127),
        ProductItem(name: "product_mullet".localized, category: categories[5], proteins: 21, fats: 0.4, carbohydrates: 0, calories: 124),
        ProductItem(name: "product_coho_salmon".localized, category: categories[5], proteins: 21.6, fats: 5.9, carbohydrates: 0, calories: 146),
        ProductItem(name: "product_baltic_sprat".localized, category: categories[5], proteins: 14.1, fats: 9, carbohydrates: 0, calories: 137),
        ProductItem(name: "product_caspian_sprat".localized, category: categories[5], proteins: 18.5, fats: 13.1, carbohydrates: 0, calories: 192),
        ProductItem(name: "product_whale_meat".localized, category: categories[5], proteins: 22.5, fats: 3.2, carbohydrates: 0, calories: 119),
        ProductItem(name: "product_kamchatka_crab_meat".localized, category: categories[5], proteins: 18.2, fats: 1, carbohydrates: 0, calories: 82),
        ProductItem(name: "product_shrimp".localized, category: categories[5], proteins: 17.0, fats: 0.6, carbohydrates: 0, calories: 80),
        ProductItem(name: "product_lobster".localized, category: categories[5], proteins: 18.8, fats: 1.3, carbohydrates: 0.5, calories: 89),
        ProductItem(name: "product_boiled_lobster".localized, category: categories[5], proteins: 20.5, fats: 0.7, carbohydrates: 0.3, calories: 90),
        ProductItem(name: "product_ice_fish".localized, category: categories[5], proteins: 15.5, fats: 1.4, carbohydrates: 0, calories: 75),
        ProductItem(name: "product_lemongrass_fish".localized, category: categories[5], proteins: 15.9, fats: 0.4, carbohydrates: 0, calories: 67),
        ProductItem(name: "product_bream".localized, category: categories[5], proteins: 17.1, fats: 4.1, carbohydrates: 0, calories: 105),
        ProductItem(name: "product_lobster_tail".localized, category: categories[5], proteins: 18.8, fats: 0.9, carbohydrates: 0.5, calories: 90),
        ProductItem(name: "product_atlantic_salmon".localized, category: categories[5], proteins: 20, fats: 8.1, carbohydrates: 0, calories: 153),
        ProductItem(name: "product_salmon".localized, category: categories[5], proteins: 19.8, fats: 6.3, carbohydrates: 0, calories: 142),
        ProductItem(name: "product_macrourus_fish".localized, category: categories[5], proteins: 13.2, fats: 0.8, carbohydrates: 0, calories: 60),
        ProductItem(name: "product_mussels".localized, category: categories[5], proteins: 11.5, fats: 2, carbohydrates: 3.3, calories: 77),
        ProductItem(name: "product_pollock".localized, category: categories[5], proteins: 15.9, fats: 0.9, carbohydrates: 0, calories: 72),
        ProductItem(name: "product_spring_capelin".localized, category: categories[5], proteins: 13.1, fats: 7.1, carbohydrates: 0, calories: 116),
        ProductItem(name: "product_autumn_capelin".localized, category: categories[5], proteins: 13.6, fats: 18.1, carbohydrates: 0, calories: 217),
        ProductItem(name: "product_fish_milt".localized, category: categories[5], proteins: 16, fats: 2.9, carbohydrates: 0, calories: 90),
        ProductItem(name: "product_scallop".localized, category: categories[5], proteins: 17, fats: 2, carbohydrates: 3, calories: 92),
        ProductItem(name: "product_navaga_fish".localized, category: categories[5], proteins: 19.2, fats: 1.6, carbohydrates: 0, calories: 91),
        ProductItem(name: "product_burbot".localized, category: categories[5], proteins: 18.8, fats: 0.6, carbohydrates: 0, calories: 81),
        ProductItem(name: "product_red_salmon".localized, category: categories[5], proteins: 20.3, fats: 8.4, carbohydrates: 0, calories: 157),
        ProductItem(name: "product_sea_bass".localized, category: categories[5], proteins: 18.2, fats: 3.3, carbohydrates: 0, calories: 103),
        ProductItem(name: "product_river_perch".localized, category: categories[5], proteins: 18.5, fats: 0.9, carbohydrates: 0, calories: 82),
        ProductItem(name: "product_lobster_boiled".localized, category: categories[5], proteins: 20.5, fats: 0.7, carbohydrates: 0.3, calories: 90),
        ProductItem(name: "product_caspian_sturgeon".localized, category: categories[5], proteins: 16.4, fats: 10.9, carbohydrates: 0, calories: 164),
        ProductItem(name: "product_sturgeon".localized, category: categories[5], proteins: 15.8, fats: 15.4, carbohydrates: 0, calories: 202),
        ProductItem(name: "product_halibut".localized, category: categories[5], proteins: 18.9, fats: 3, carbohydrates: 0, calories: 103),
        ProductItem(name: "product_pangasius".localized, category: categories[5], proteins: 15.7, fats: 4.8, carbohydrates: 0, calories: 112),
        ProductItem(name: "product_petrushka_fish".localized, category: categories[5], proteins: 19.8, fats: 1.2, carbohydrates: 0, calories: 92),
        ProductItem(name: "product_pikul_fish".localized, category: categories[5], proteins: 20.5, fats: 2, carbohydrates: 0, calories: 110),
        // Продукты из категории 7
        ProductItem(name: "product_dried_vobla".localized, category: categories[5], proteins: 46.4, fats: 5.5, carbohydrates: 0, calories: 235),
        ProductItem(name: "product_hot_smoked_pink_salmon".localized, category: categories[5], proteins: 23.2, fats: 7.6, carbohydrates: 0, calories: 161),
        ProductItem(name: "product_salted_pink_salmon".localized, category: categories[5], proteins: 22.1, fats: 9.0, carbohydrates: 0, calories: 169),
        ProductItem(name: "product_dried_squid".localized, category: categories[5], proteins: 62, fats: 2, carbohydrates: 5, calories: 286),
        ProductItem(name: "product_salted_chum_salmon".localized, category: categories[5], proteins: 24.3, fats: 9.6, carbohydrates: 0, calories: 184),
        ProductItem(name: "product_hot_smoked_baltic_sprat".localized, category: categories[5], proteins: 21.3, fats: 8.5, carbohydrates: 0, calories: 162),
        ProductItem(name: "product_salted_baltic_sprat".localized, category: categories[5], proteins: 17.1, fats: 7.6, carbohydrates: 0, calories: 137),
        ProductItem(name: "product_spiced_salted_sprat".localized, category: categories[5], proteins: 14.8, fats: 10.5, carbohydrates: 0, calories: 154),
        ProductItem(name: "product_crab_sticks".localized, category: categories[5], proteins: 6.2, fats: 0.38, carbohydrates: 10, calories: 70),
        ProductItem(name: "product_red_salmon_caviar".localized, category: categories[5], proteins: 32, fats: 15, carbohydrates: 0, calories: 263),
        ProductItem(name: "product_pollock_caviar".localized, category: categories[5], proteins: 27.9, fats: 1.8, carbohydrates: 1.1, calories: 132),
        ProductItem(name: "product_santa_bremor_capelin_caviar".localized, category: categories[5], proteins: 8.1, fats: 36.9, carbohydrates: 0, calories: 365),
        ProductItem(name: "product_herring_caviar".localized, category: categories[5], proteins: 31.6, fats: 10.3, carbohydrates: 0, calories: 222),
        ProductItem(name: "product_black_sturgeon_caviar".localized, category: categories[5], proteins: 28.4, fats: 9.3, carbohydrates: 0.6, calories: 200),
        ProductItem(name: "product_pressed_sturgeon_caviar".localized, category: categories[5], proteins: 38.2, fats: 14.5, carbohydrates: 1.5, calories: 289),
        ProductItem(name: "product_pike_caviar".localized, category: categories[5], proteins: 17.3, fats: 2, carbohydrates: 0, calories: 87),
        ProductItem(name: "product_salted_salmon".localized, category: categories[5], proteins: 21, fats: 20.5, carbohydrates: 0, calories: 269),
        ProductItem(name: "product_dried_bream".localized, category: categories[5], proteins: 42, fats: 5.9, carbohydrates: 0, calories: 221),
        ProductItem(name: "product_hot_smoked_bream".localized, category: categories[5], proteins: 32.8, fats: 4.5, carbohydrates: 0, calories: 172),
        ProductItem(name: "product_cold_smoked_bream".localized, category: categories[5], proteins: 29.7, fats: 4.6, carbohydrates: 0, calories: 160),
        ProductItem(name: "product_smoked_butterfish".localized, category: categories[5], proteins: 18, fats: 12, carbohydrates: 0, calories: 180),
        ProductItem(name: "product_smoked_capelin".localized, category: categories[5], proteins: 18, fats: 22, carbohydrates: 0, calories: 270),
        ProductItem(name: "product_hot_smoked_sea_bass".localized, category: categories[5], proteins: 23.5, fats: 8, carbohydrates: 0, calories: 166),
        ProductItem(name: "product_cold_smoked_sturgeon".localized, category: categories[5], proteins: 20.4, fats: 12.5, carbohydrates: 0, calories: 194),
        ProductItem(name: "product_smoked_sprat".localized, category: categories[5], proteins: 25.4, fats: 5.6, carbohydrates: 0, calories: 152),
        ProductItem(name: "product_hot_smoked_herring".localized, category: categories[5], proteins: 21.8, fats: 14.3, carbohydrates: 0, calories: 215),
        ProductItem(name: "product_medium_salted_atlantic_herring".localized, category: categories[5], proteins: 17, fats: 8.5, carbohydrates: 0, calories: 145),
        ProductItem(name: "product_medium_salted_pacific_herring".localized, category: categories[5], proteins: 17.4, fats: 17.1, carbohydrates: 0, calories: 224),
        ProductItem(name: "product_salted_herring".localized, category: categories[5], proteins: 19.8, fats: 15.4, carbohydrates: 0, calories: 217),
        ProductItem(name: "product_salted_salmon_with_head".localized, category: categories[5], proteins: 22.5, fats: 12.5, carbohydrates: 0, calories: 202),
        ProductItem(name: "product_smoked_salmon".localized, category: categories[5], proteins: 22.5, fats: 12.5, carbohydrates: 0, calories: 202),
        ProductItem(name: "product_hot_smoked_mackerel".localized, category: categories[5], proteins: 22.1, fats: 23.8, carbohydrates: 0, calories: 307),
        ProductItem(name: "product_cold_smoked_mackerel".localized, category: categories[5], proteins: 23.4, fats: 6.4, carbohydrates: 0, calories: 150),
        ProductItem(name: "product_smoked_trout".localized, category: categories[5], proteins: 26, fats: 3.1, carbohydrates: 0.5, calories: 132),
        ProductItem(name: "product_lightly_salted_trout".localized, category: categories[5], proteins: 20.6, fats: 10.1, carbohydrates: 0, calories: 186),
        ProductItem(name: "product_fatty_lightly_salted_trout".localized, category: categories[5], proteins: 23, fats: 15, carbohydrates: 0, calories: 227),
        ProductItem(name: "product_salted_anchovy".localized, category: categories[5], proteins: 21.2, fats: 9, carbohydrates: 0, calories: 166)
    ],
    categories[6]: [
            ProductItem(name: "product_bullheads_in_tomato_sauce".localized, category: categories[6], proteins: 17.5, fats: 2, carbohydrates: 0, calories: 88),
            ProductItem(name: "product_natural_pink_salmon".localized, category: categories[6], proteins: 20.9, fats: 5.8, carbohydrates: 0, calories: 136),
            ProductItem(name: "product_pink_salmon_in_tomato_sauce".localized, category: categories[6], proteins: 15, fats: 6, carbohydrates: 4.1, calories: 130),
            ProductItem(name: "product_squid_canned".localized, category: categories[6], proteins: 15, fats: 1.5, carbohydrates: 1.7, calories: 76),
            ProductItem(name: "product_sprats_in_tomato_sauce".localized, category: categories[6], proteins: 14, fats: 12, carbohydrates: 4.5, calories: 182),
            ProductItem(name: "product_crabs_canned".localized, category: categories[6], proteins: 18.7, fats: 1.1, carbohydrates: 0.1, calories: 85),
            ProductItem(name: "product_salmon_canned".localized, category: categories[6], proteins: 20.6, fats: 6.3, carbohydrates: 0, calories: 144),
            ProductItem(name: "product_mussels_canned".localized, category: categories[6], proteins: 17.5, fats: 2, carbohydrates: 0, calories: 88),
            ProductItem(name: "product_seaweed_canned".localized, category: categories[6], proteins: 0.8, fats: 5.1, carbohydrates: 0, calories: 49),
            ProductItem(name: "product_pollock_liver_canned".localized, category: categories[6], proteins: 6, fats: 50, carbohydrates: 0, calories: 474),
            ProductItem(name: "product_cod_liver_canned".localized, category: categories[6], proteins: 4.2, fats: 65.7, carbohydrates: 1.2, calories: 613),
            ProductItem(name: "product_saury_in_oil".localized, category: categories[6], proteins: 18.3, fats: 23.3, carbohydrates: 0, calories: 283),
            ProductItem(name: "product_sardines_with_oil".localized, category: categories[6], proteins: 19, fats: 18, carbohydrates: 0, calories: 238),
            ProductItem(name: "product_sardines_in_oil".localized, category: categories[6], proteins: 24.1, fats: 13.9, carbohydrates: 0, calories: 221),
            ProductItem(name: "product_sardines_in_tomato_sauce".localized, category: categories[6], proteins: 17, fats: 9.9, carbohydrates: 1.4, calories: 162),
            ProductItem(name: "product_herring_canned".localized, category: categories[6], proteins: 17.5, fats: 2, carbohydrates: 0, calories: 88),
            ProductItem(name: "product_herring_in_vegetable_oil".localized, category: categories[6], proteins: 16.4, fats: 26.5, carbohydrates: 0, calories: 301),
            ProductItem(name: "product_natural_mackerel".localized, category: categories[6], proteins: 17.7, fats: 14.4, carbohydrates: 0, calories: 200),
            ProductItem(name: "product_mackerel_in_oil".localized, category: categories[6], proteins: 14.4, fats: 28.9, carbohydrates: 0, calories: 318),
            ProductItem(name: "product_horse_mackerel_in_oil".localized, category: categories[6], proteins: 15.6, fats: 27.4, carbohydrates: 0, calories: 309),
            ProductItem(name: "product_horse_mackerel_in_tomato_sauce".localized, category: categories[6], proteins: 14.8, fats: 2.3, carbohydrates: 73, calories: 110),
            ProductItem(name: "product_natural_tuna".localized, category: categories[6], proteins: 22.5, fats: 0.7, carbohydrates: 0, calories: 96),
            ProductItem(name: "product_tuna_in_oil".localized, category: categories[6], proteins: 22, fats: 15.9, carbohydrates: 0, calories: 232),
            ProductItem(name: "product_sprats_in_oil".localized, category: categories[6], proteins: 17.4, fats: 32.4, carbohydrates: 0.4, calories: 363),
            ProductItem(name: "product_sprat_pate".localized, category: categories[6], proteins: 12, fats: 14, carbohydrates: 5.3, calories: 195)
        ],
    categories[7]: [
            ProductItem(name: "product_chicken_egg".localized, category: categories[7], proteins: 12.7, fats: 10.9, carbohydrates: 0.7, calories: 157),
            ProductItem(name: "product_egg_white".localized, category: categories[7], proteins: 11.1, fats: 0, carbohydrates: 0, calories: 44),
            ProductItem(name: "product_egg_yolk".localized, category: categories[7], proteins: 16.2, fats: 31.2, carbohydrates: 1, calories: 354),
            ProductItem(name: "product_boiled_chicken_egg".localized, category: categories[7], proteins: 12.7, fats: 11.5, carbohydrates: 0.7, calories: 157),
            ProductItem(name: "product_fried_chicken_egg_no_oil".localized, category: categories[7], proteins: 14.6, fats: 12.6, carbohydrates: 0.8, calories: 174),
            ProductItem(name: "product_quail_egg".localized, category: categories[7], proteins: 11.9, fats: 13.1, carbohydrates: 0.6, calories: 168),
            ProductItem(name: "product_goose_egg".localized, category: categories[7], proteins: 13.9, fats: 13.3, carbohydrates: 1.4, calories: 185),
            ProductItem(name: "product_duck_egg".localized, category: categories[7], proteins: 13.3, fats: 14.5, carbohydrates: 0.1, calories: 185),
            ProductItem(name: "product_ostrich_egg".localized, category: categories[7], proteins: 12.2, fats: 11.7, carbohydrates: 0.7, calories: 118),
            ProductItem(name: "product_melange".localized, category: categories[7], proteins: 12.7, fats: 11.5, carbohydrates: 0.7, calories: 157),
            ProductItem(name: "product_egg_powder".localized, category: categories[7], proteins: 46, fats: 37.3, carbohydrates: 4.5, calories: 542)
        ],
    categories[8]: [
        ProductItem(name: "Масло сливочное", category: categories[8], proteins: 0.5, fats: 78.0, carbohydrates: 0.8, calories: 709),
        ProductItem(name: "Масло сливочное \"Валио\"", category: categories[8], proteins: 0.7, fats: 82.0, carbohydrates: 0.7, calories: 740),
        ProductItem(name: "Масло топленое", category: categories[8], proteins: 0.2, fats: 99.0, carbohydrates: 0, calories: 892),
        ProductItem(name: "Масло шоколадное", category: categories[8], proteins: 1.5, fats: 62.0, carbohydrates: 18.6, calories: 642),
        ProductItem(name: "Масло оливковое", category: categories[8], proteins: 0, fats: 99.8, carbohydrates: 0, calories: 898),
        ProductItem(name: "Масло подсолнечное", category: categories[8], proteins: 0, fats: 99.9, carbohydrates: 0, calories: 899),
        ProductItem(name: "Маргарин", category: categories[8], proteins: 0.3, fats: 82.0, carbohydrates: 0.8, calories: 743),
        ProductItem(name: "Спред", category: categories[8], proteins: 0, fats: 40.0, carbohydrates: 0, calories: 360),
        ProductItem(name: "Майонез", category: categories[8], proteins: 1.4, fats: 47.0, carbohydrates: 2.6, calories: 450),
        ProductItem(name: "Майонез легкий", category: categories[8], proteins: 0.3, fats: 8.0, carbohydrates: 1.9, calories: 110),
        ProductItem(name: "Жир говяжий, свиной, бараний топленые", category: categories[8], proteins: 0, fats: 99.7, carbohydrates: 0, calories: 897),
        ProductItem(name: "Жир кулинарный, кондитерский", category: categories[8], proteins: 0, fats: 99.7, carbohydrates: 0, calories: 897),
        ProductItem(name: "Жир рыбий", category: categories[8], proteins: 0, fats: 100.0, carbohydrates: 0, calories: 902),
        ProductItem(name: "Сало", category: categories[8], proteins: 2.4, fats: 89.0, carbohydrates: 0, calories: 797),
        ProductItem(name: "Шпик", category: categories[8], proteins: 1.4, fats: 92.8, carbohydrates: 0, calories: 841)
    ],
    categories[9]: [
        ProductItem(name: "Артишок", category: categories[9], proteins: 1.2, fats: 0.1, carbohydrates: 6, calories: 28),
        ProductItem(name: "Базилик", category: categories[9], proteins: 2.5, fats: 0.6, carbohydrates: 4.3, calories: 27),
        ProductItem(name: "Баклажаны", category: categories[9], proteins: 1.2, fats: 0.1, carbohydrates: 4.5, calories: 24),
        ProductItem(name: "Батат (сладкий картофель)", category: categories[9], proteins: 1.6, fats: 0.05, carbohydrates: 17.1, calories: 86),
        ProductItem(name: "Батат отварной без кожуры", category: categories[9], proteins: 1.4, fats: 0.14, carbohydrates: 15.2, calories: 76),
        ProductItem(name: "Брюква", category: categories[9], proteins: 1.2, fats: 0.1, carbohydrates: 7.7, calories: 37),
        ProductItem(name: "Горчица листовая", category: categories[9], proteins: 2.9, fats: 0.4, carbohydrates: 1.5, calories: 27),
        ProductItem(name: "Дайкон", category: categories[9], proteins: 1.2, fats: 0, carbohydrates: 4.1, calories: 21),
        ProductItem(name: "Имбирь, корень сырой", category: categories[9], proteins: 1.8, fats: 0.75, carbohydrates: 15.8, calories: 80),
        ProductItem(name: "Кабачки", category: categories[9], proteins: 0.6, fats: 0.3, carbohydrates: 4.6, calories: 24),
        ProductItem(name: "Капуста белокочанная", category: categories[9], proteins: 1.8, fats: 0.1, carbohydrates: 4.7, calories: 28),
        ProductItem(name: "Капуста квашеная", category: categories[9], proteins: 1.8, fats: 0.1, carbohydrates: 3, calories: 23),
        ProductItem(name: "Капуста вареная", category: categories[9], proteins: 1.4, fats: 0.1, carbohydrates: 4.2, calories: 24),
        ProductItem(name: "Капуста брокколи", category: categories[9], proteins: 2.8, fats: 0.37, carbohydrates: 6.6, calories: 34),
        ProductItem(name: "Капуста брокколи вареная", category: categories[9], proteins: 2.38, fats: 0.4, carbohydrates: 7.18, calories: 35),
        ProductItem(name: "Капуста брокколизамороженная, вареная", category: categories[9], proteins: 3.1, fats: 0.12, carbohydrates: 5.35, calories: 28),
        ProductItem(name: "Капуста брюссельская", category: categories[9], proteins: 3.4, fats: 0.3, carbohydrates: 8.9, calories: 43),
        ProductItem(name: "Капуста брюссельскаязамороженная, вареная", category: categories[9], proteins: 3.6, fats: 0.4, carbohydrates: 8.3, calories: 42),
        ProductItem(name: "Капуста кольраби", category: categories[9], proteins: 2.8, fats: 0.1, carbohydrates: 7.9, calories: 44),
        ProductItem(name: "Капуста краснокочанная", category: categories[9], proteins: 0.8, fats: 0.2, carbohydrates: 5.1, calories: 26),
        ProductItem(name: "Капуста пекинская", category: categories[9], proteins: 1.2, fats: 0.2, carbohydrates: 2, calories: 16),
        ProductItem(name: "Капуста савойская", category: categories[9], proteins: 1.2, fats: 0.1, carbohydrates: 5.6, calories: 28),
        ProductItem(name: "Капуста цветная", category: categories[9], proteins: 2.5, fats: 0.3, carbohydrates: 4.2, calories: 30),
        ProductItem(name: "Капуста листовая кале (кейл, Kale)", category: categories[9], proteins: 2.8, fats: 0.6, carbohydrates: 6.6, calories: 42),
        ProductItem(name: "Капуста листовая коллардс(Collards)", category: categories[9], proteins: 3, fats: 0.6, carbohydrates: 1.4, calories: 32),
        ProductItem(name: "Картофель", category: categories[9], proteins: 2, fats: 0.4, carbohydrates: 16.3, calories: 77),
        ProductItem(name: "Картофель отварной", category: categories[9], proteins: 2, fats: 0.4, carbohydrates: 15.8, calories: 75),
        ProductItem(name: "Кресс-салат", category: categories[9], proteins: 2.3, fats: 0.1, carbohydrates: 0.8, calories: 11),
        ProductItem(name: "Кукуруза сырая", category: categories[9], proteins: 3.3, fats: 1.35, carbohydrates: 16.7, calories: 86),
        ProductItem(name: "Лук зеленый", category: categories[9], proteins: 1.3, fats: 0.1, carbohydrates: 3.2, calories: 20),
        ProductItem(name: "Лук репчатый", category: categories[9], proteins: 1.4, fats: 0.2, carbohydrates: 8.2, calories: 41),
        ProductItem(name: "Лук репчатый красный", category: categories[9], proteins: 1.4, fats: 0.1, carbohydrates: 9.1, calories: 42),
        ProductItem(name: "Лук порей", category: categories[9], proteins: 2, fats: 0.2, carbohydrates: 6.3, calories: 36),
        ProductItem(name: "Мангольд", category: categories[9], proteins: 1.8, fats: 0.2, carbohydrates: 2.1, calories: 19),
        ProductItem(name: "Морковь", category: categories[9], proteins: 1.3, fats: 0.1, carbohydrates: 6.9, calories: 35),
        ProductItem(name: "Морковь отварная", category: categories[9], proteins: 1.3, fats: 0.1, carbohydrates: 6.4, calories: 33),
        ProductItem(name: "Огурец грунтовый", category: categories[9], proteins: 0.8, fats: 0.1, carbohydrates: 3.6, calories: 16),
        ProductItem(name: "Огурец маринованный", category: categories[9], proteins: 0.8, fats: 0.1, carbohydrates: 2.7, calories: 15),
        ProductItem(name: "Огурец соленый", category: categories[9], proteins: 0.8, fats: 0.1, carbohydrates: 2.5, calories: 13),
        ProductItem(name: "Оливки", category: categories[9], proteins: 1, fats: 10.7, carbohydrates: 6, calories: 115),
        ProductItem(name: "Перец сладкий", category: categories[9], proteins: 0.9, fats: 0.3, carbohydrates: 5.9, calories: 27),
        ProductItem(name: "Перец сладкий жареный", category: categories[9], proteins: 1, fats: 0.4, carbohydrates: 4.9, calories: 31),
        ProductItem(name: "Помидоры", category: categories[9], proteins: 0.9, fats: 0.2, carbohydrates: 3.9, calories: 20),
        ProductItem(name: "Помидоры сушеные", category: categories[9], proteins: 4.6, fats: 3.3, carbohydrates: 31.8, calories: 258),
        ProductItem(name: "Руккола", category: categories[9], proteins: 2.6, fats: 0.7, carbohydrates: 3.7, calories: 25),
        ProductItem(name: "Сельдерей", category: categories[9], proteins: 1.5, fats: 0.2, carbohydrates: 3.3, calories: 16),
        ProductItem(name: "Томаты черри", category: categories[9], proteins: 0.9, fats: 0.2, carbohydrates: 3.9, calories: 18),
        ProductItem(name: "Тыква", category: categories[9], proteins: 1.2, fats: 0.1, carbohydrates: 6.5, calories: 26),
        ProductItem(name: "Тыква запеченная", category: categories[9], proteins: 1.1, fats: 0.1, carbohydrates: 6.4, calories: 27),
        ProductItem(name: "Шпинат", category: categories[9], proteins: 2.9, fats: 0.4, carbohydrates: 3.6, calories: 23),
        ProductItem(name: "Шпинат вареный", category: categories[9], proteins: 3, fats: 0.3, carbohydrates: 3.8, calories: 23),
        ProductItem(name: "Ямс", category: categories[9], proteins: 1.5, fats: 0.2, carbohydrates: 27.9, calories: 118),
        // Грибы
        ProductItem(name: "Грибы белые свежие", category: categories[9], proteins: 3.7, fats: 1.7, carbohydrates: 1.1, calories: 34),
        ProductItem(name: "Грибы белые сушеные", category: categories[9], proteins: 30.3, fats: 14.3, carbohydrates: 9.0, calories: 286),
        ProductItem(name: "Вешенки свежие", category: categories[9], proteins: 2.5, fats: 0.3, carbohydrates: 6.5, calories: 3.8),
        ProductItem(name: "Грузди свежие", category: categories[9], proteins: 1.8, fats: 0.5, carbohydrates: 0.8, calories: 16),
        ProductItem(name: "Лисички", category: categories[9], proteins: 1.5, fats: 1.0, carbohydrates: 1.0, calories: 19),
        ProductItem(name: "Опята", category: categories[9], proteins: 2.2, fats: 1.2, carbohydrates: 0.5, calories: 22),
        ProductItem(name: "Подберезовики", category: categories[9], proteins: 2.1, fats: 0.8, carbohydrates: 1.2, calories: 20),
        ProductItem(name: "Подберезовики сушеные", category: categories[9], proteins: 23.5, fats: 9.2, carbohydrates: 14.3, calories: 231),
        ProductItem(name: "Подосиновики", category: categories[9], proteins: 3.3, fats: 0.5, carbohydrates: 1.2, calories: 22),
        ProductItem(name: "Подосиновики сушеные", category: categories[9], proteins: 35.4, fats: 5.4, carbohydrates: 33.2, calories: 315),
        ProductItem(name: "Сморчки", category: categories[9], proteins: 1.7, fats: 0.3, carbohydrates: 4.2, calories: 27),
        ProductItem(name: "Сыроежки", category: categories[9], proteins: 1.7, fats: 0.7, carbohydrates: 1.5, calories: 19),
        ProductItem(name: "Шампиньоны", category: categories[9], proteins: 4.3, fats: 1.0, carbohydrates: 0.1, calories: 27)
    ],
    categories[10]: [
        ProductItem(name: "Икра баклажанная", category: categories[10], proteins: 1.7, fats: 13.3, carbohydrates: 5.1, calories: 148),
        ProductItem(name: "Икра кабачковая", category: categories[10], proteins: 1.6, fats: 8.15, carbohydrates: 7.0, calories: 109.5), // Среднее значение
        ProductItem(name: "Горошек зеленый", category: categories[10], proteins: 3.1, fats: 0.2, carbohydrates: 6.5, calories: 40),
        ProductItem(name: "Кукуруза сладкая", category: categories[10], proteins: 2.95, fats: 0.65, carbohydrates: 17.85, calories: 92), // Среднее значение
        ProductItem(name: "Огурцы маринованные", category: categories[10], proteins: 0.8, fats: 1.3, carbohydrates: 0.0, calories: 16),
        ProductItem(name: "Помидоры маринованные", category: categories[10], proteins: 0.5, fats: 0.1, carbohydrates: 2.1, calories: 10),
        ProductItem(name: "Свекла", category: categories[10], proteins: 1.05, fats: 0.05, carbohydrates: 6.225, calories: 31.5) // Среднее значение
    ],
    categories[11]: [
        ProductItem(name: "Арбуз", category: categories[11], proteins: 0.6, fats: 0.1, carbohydrates: 5.8, calories: 27),
        ProductItem(name: "Абрикосы", category: categories[11], proteins: 0.9, fats: 0.1, carbohydrates: 9, calories: 44),
        ProductItem(name: "Авокадо", category: categories[11], proteins: 2, fats: 14.6, carbohydrates: 8.5, calories: 160),
        ProductItem(name: "Айва", category: categories[11], proteins: 0.6, fats: 0.5, carbohydrates: 9.6, calories: 48),
        ProductItem(name: "Алыча", category: categories[11], proteins: 0.2, fats: 0.1, carbohydrates: 7.9, calories: 34),
        ProductItem(name: "Ананас", category: categories[11], proteins: 0.4, fats: 0.2, carbohydrates: 11.5, calories: 52),
        ProductItem(name: "Апельсины", category: categories[11], proteins: 0.9, fats: 0.2, carbohydrates: 8.1, calories: 43),
        ProductItem(name: "Банан", category: categories[11], proteins: 1.5, fats: 0.5, carbohydrates: 21, calories: 96),
        ProductItem(name: "Виноград", category: categories[11], proteins: 0.6, fats: 0.6, carbohydrates: 15.4, calories: 72),
        ProductItem(name: "Вишня", category: categories[11], proteins: 0.8, fats: 0.2, carbohydrates: 10.6, calories: 52),
        ProductItem(name: "Гранат", category: categories[11], proteins: 0.7, fats: 0.6, carbohydrates: 14.5, calories: 72),
        ProductItem(name: "Грейпфрут", category: categories[11], proteins: 0.7, fats: 0.2, carbohydrates: 6.5, calories: 35),
        ProductItem(name: "Груша", category: categories[11], proteins: 0.4, fats: 0.3, carbohydrates: 10.3, calories: 47),
        ProductItem(name: "Дуриан", category: categories[11], proteins: 1.5, fats: 5.3, carbohydrates: 23.3, calories: 147),
        ProductItem(name: "Дыня", category: categories[11], proteins: 0.6, fats: 0.3, carbohydrates: 7.4, calories: 35),
        ProductItem(name: "Инжир свежий", category: categories[11], proteins: 0.7, fats: 0.2, carbohydrates: 12, calories: 54),
        ProductItem(name: "Киви", category: categories[11], proteins: 0.8, fats: 0.4, carbohydrates: 8.1, calories: 47),
        ProductItem(name: "Кумкват", category: categories[11], proteins: 1.9, fats: 0.9, carbohydrates: 13.4, calories: 71),
        ProductItem(name: "Лимон", category: categories[11], proteins: 0.9, fats: 0.1, carbohydrates: 3, calories: 34),
        ProductItem(name: "Личи", category: categories[11], proteins: 0.8, fats: 0.4, carbohydrates: 15.2, calories: 66),
        ProductItem(name: "Манго", category: categories[11], proteins: 0.8, fats: 0.4, carbohydrates: 13.4, calories: 60),
        ProductItem(name: "Мандарины", category: categories[11], proteins: 0.8, fats: 0.2, carbohydrates: 7.5, calories: 38),
        ProductItem(name: "Маракуйя", category: categories[11], proteins: 2.4, fats: 0.4, carbohydrates: 13.4, calories: 68),
        ProductItem(name: "Нектарин", category: categories[11], proteins: 1.1, fats: 0.3, carbohydrates: 9, calories: 44),
        ProductItem(name: "Папайя", category: categories[11], proteins: 0.5, fats: 0.26, carbohydrates: 9.1, calories: 43),
        ProductItem(name: "Персик", category: categories[11], proteins: 0.9, fats: 0.1, carbohydrates: 9.5, calories: 45),
        ProductItem(name: "Помело", category: categories[11], proteins: 0.8, fats: 0.04, carbohydrates: 8.6, calories: 38),
        ProductItem(name: "Слива", category: categories[11], proteins: 0.8, fats: 0.3, carbohydrates: 9.6, calories: 49),
        ProductItem(name: "Терн", category: categories[11], proteins: 1.5, fats: 0.3, carbohydrates: 9.4, calories: 54),
        ProductItem(name: "Фейхоа", category: categories[11], proteins: 0.7, fats: 0.4, carbohydrates: 8.8, calories: 61),
        ProductItem(name: "Хурма", category: categories[11], proteins: 0.5, fats: 0.4, carbohydrates: 15.3, calories: 67),
        ProductItem(name: "Черешня", category: categories[11], proteins: 1.1, fats: 0.4, carbohydrates: 10.6, calories: 52),
        ProductItem(name: "Яблоки", category: categories[11], proteins: 0.4, fats: 0.4, carbohydrates: 9.8, calories: 47),
        ProductItem(name: "Брусника", category: categories[11], proteins: 0.7, fats: 0.5, carbohydrates: 8.2, calories: 46),
        ProductItem(name: "Голубика", category: categories[11], proteins: 1, fats: 0.5, carbohydrates: 6.6, calories: 39),
        ProductItem(name: "Ежевика", category: categories[11], proteins: 1.5, fats: 0.5, carbohydrates: 4.4, calories: 34),
        ProductItem(name: "Клубника", category: categories[11], proteins: 0.8, fats: 0.4, carbohydrates: 7.5, calories: 41),
        ProductItem(name: "Клюква", category: categories[11], proteins: 0.5, fats: 0.2, carbohydrates: 3.7, calories: 28),
        ProductItem(name: "Крыжовник", category: categories[11], proteins: 0.7, fats: 0.2, carbohydrates: 9.1, calories: 45),
        ProductItem(name: "Малина", category: categories[11], proteins: 0.8, fats: 0.5, carbohydrates: 8.3, calories: 46),
        ProductItem(name: "Морошка", category: categories[11], proteins: 0.8, fats: 0.9, carbohydrates: 7.4, calories: 40),
        ProductItem(name: "Облепиха", category: categories[11], proteins: 1.2, fats: 5.4, carbohydrates: 5.7, calories: 82),
        ProductItem(name: "Смородина белая", category: categories[11], proteins: 0.5, fats: 0.2, carbohydrates: 8, calories: 42),
        ProductItem(name: "Смородина красная", category: categories[11], proteins: 0.6, fats: 0.2, carbohydrates: 7.7, calories: 43),
        ProductItem(name: "Смородина черная", category: categories[11], proteins: 1, fats: 0.4, carbohydrates: 7.3, calories: 44),
        ProductItem(name: "Черника", category: categories[11], proteins: 1.1, fats: 0.6, carbohydrates: 7.6, calories: 44),
        ProductItem(name: "Шиповник свежий", category: categories[11], proteins: 1.6, fats: 0.7, carbohydrates: 22.4, calories: 109),
        ProductItem(name: "Шиповник сухой", category: categories[11], proteins: 3.4, fats: 1.4, carbohydrates: 48.3, calories: 284)
    ],
    categories[12]: [
        ProductItem(name: "Арахис", category: categories[12], proteins: 26.3, fats: 45.2, carbohydrates: 9.9, calories: 552),
        ProductItem(name: "Арахис жареный", category: categories[12], proteins: 26, fats: 52, carbohydrates: 13.4, calories: 626),
        ProductItem(name: "Бразильский орех", category: categories[12], proteins: 14.3, fats: 67.1, carbohydrates: 4.2, calories: 659),
        ProductItem(name: "Грецкие орехи", category: categories[12], proteins: 16.2, fats: 60.8, carbohydrates: 11.1, calories: 656),
        ProductItem(name: "Кедровые орехи", category: categories[12], proteins: 13.7, fats: 64.1, carbohydrates: 9.4, calories: 673),
        ProductItem(name: "Кешью", category: categories[12], proteins: 18.5, fats: 48.5, carbohydrates: 22.5, calories: 600),
        ProductItem(name: "Кешью жареный", category: categories[12], proteins: 17.5, fats: 42.2, carbohydrates: 30.5, calories: 572),
        ProductItem(name: "Кокосовый орех сырой", category: categories[12], proteins: 3.3, fats: 33.5, carbohydrates: 6.2, calories: 354),
        ProductItem(name: "Лесной орех (лещина)", category: categories[12], proteins: 13, fats: 62.6, carbohydrates: 9.3, calories: 653),
        ProductItem(name: "Миндальный орех", category: categories[12], proteins: 18.6, fats: 53.7, carbohydrates: 13, calories: 609),
        ProductItem(name: "Миндальный орех жареный", category: categories[12], proteins: 22.4, fats: 55.9, carbohydrates: 12.3, calories: 642),
        ProductItem(name: "Миндальные лепестки", category: categories[12], proteins: 22, fats: 58, carbohydrates: 12, calories: 650),
        ProductItem(name: "Орех макадамия", category: categories[12], proteins: 7.9, fats: 75.8, carbohydrates: 5.2, calories: 718),
        ProductItem(name: "Орехи пекан", category: categories[12], proteins: 9.2, fats: 72, carbohydrates: 4.3, calories: 691),
        ProductItem(name: "Семечки подсолнечника, ядра сушеные", category: categories[12], proteins: 20.8, fats: 51.5, carbohydrates: 17.4, calories: 584),
        ProductItem(name: "Семечки тыквенные, ядра сушеные", category: categories[12], proteins: 30.2, fats: 49.1, carbohydrates: 9.3, calories: 559),
        ProductItem(name: "Семена конопли очищенные", category: categories[12], proteins: 31.6, fats: 48.7, carbohydrates: 4.7, calories: 553),
        ProductItem(name: "Семена конопли неочищенные", category: categories[12], proteins: 20.1, fats: 32.5, carbohydrates: 14, calories: 429),
        ProductItem(name: "Семена кунжута", category: categories[12], proteins: 19.4, fats: 48.7, carbohydrates: 12.2, calories: 565),
        ProductItem(name: "Семена льна", category: categories[12], proteins: 18.3, fats: 42.2, carbohydrates: 1.6, calories: 534),
        ProductItem(name: "Семена мака", category: categories[12], proteins: 17.5, fats: 47.5, carbohydrates: 14.5, calories: 556),
        ProductItem(name: "Семена чиа", category: categories[12], proteins: 16.5, fats: 30.7, carbohydrates: 7.7, calories: 486),
        ProductItem(name: "Фисташки сырые", category: categories[12], proteins: 20.2, fats: 45.3, carbohydrates: 16.6, calories: 560),
        ProductItem(name: "Фисташки жареные без масла с добавлением соли", category: categories[12], proteins: 21.1, fats: 45.8, carbohydrates: 17.3, calories: 569),
        ProductItem(name: "Фундук (лещина окультуренная)", category: categories[12], proteins: 15, fats: 61.5, carbohydrates: 9.4, calories: 651),
        ProductItem(name: "Фундук жареный", category: categories[12], proteins: 17.8, fats: 66.1, carbohydrates: 9.4, calories: 703),
        ProductItem(name: "Бананы сушеные", category: categories[12], proteins: 3.9, fats: 1.8, carbohydrates: 78.4, calories: 346),
        ProductItem(name: "Вишня сушеная", category: categories[12], proteins: 1.5, fats: 0, carbohydrates: 73, calories: 290),
        ProductItem(name: "Груша сушеная", category: categories[12], proteins: 2.3, fats: 0.6, carbohydrates: 62.6, calories: 270),
        ProductItem(name: "Дыня сушеная", category: categories[12], proteins: 0.7, fats: 0.1, carbohydrates: 82.2, calories: 341),
        ProductItem(name: "Изюм", category: categories[12], proteins: 2.5, fats: 0.54, carbohydrates: 67.7, calories: 296),
        ProductItem(name: "Изюм кишмиш", category: categories[12], proteins: 2.3, fats: 0.5, carbohydrates: 65.8, calories: 281),
        ProductItem(name: "Инжир сушеный", category: categories[12], proteins: 3.1, fats: 0.8, carbohydrates: 57.9, calories: 257),
        ProductItem(name: "Курага", category: categories[12], proteins: 5.2, fats: 0.3, carbohydrates: 51, calories: 232),
        ProductItem(name: "Персик сушеный", category: categories[12], proteins: 3, fats: 0.4, carbohydrates: 57.7, calories: 254),
        ProductItem(name: "Урюк", category: categories[12], proteins: 5, fats: 0.4, carbohydrates: 53, calories: 242),
        ProductItem(name: "Финики", category: categories[12], proteins: 2.5, fats: 0.5, carbohydrates: 69.2, calories: 292),
        ProductItem(name: "Чернослив (слива сушеная)", category: categories[12], proteins: 2.3, fats: 0.7, carbohydrates: 57.5, calories: 256),
        ProductItem(name: "Яблоки сушеные", category: categories[12], proteins: 2.2, fats: 0.1, carbohydrates: 59, calories: 253)
    ],
    categories[13]: [
        ProductItem(name: "Сахар-песок", category: categories[13], proteins: 0.0, fats: 0.0, carbohydrates: 99.8, calories: 399),
        ProductItem(name: "Сахар-рафинад", category: categories[13], proteins: 0.0, fats: 0.0, carbohydrates: 99.9, calories: 400),
        ProductItem(name: "Сахар тростниковый", category: categories[13], proteins: 0.0, fats: 0.0, carbohydrates: 99.7, calories: 394),
        ProductItem(name: "Варенье вишневое", category: categories[13], proteins: 0.0, fats: 0.0, carbohydrates: 64.0, calories: 256),
        ProductItem(name: "Варенье клубничное", category: categories[13], proteins: 0.3, fats: 0.0, carbohydrates: 74.0, calories: 282),
        ProductItem(name: "Варенье малиновое", category: categories[13], proteins: 0.6, fats: 0.0, carbohydrates: 70.4, calories: 270),
        ProductItem(name: "Варенье сливовое", category: categories[13], proteins: 0.7, fats: 0.0, carbohydrates: 74.6, calories: 283),
        ProductItem(name: "Варенье черничное", category: categories[13], proteins: 0.4, fats: 0.0, carbohydrates: 51.6, calories: 211),
        ProductItem(name: "Варенье из черной смородины", category: categories[13], proteins: 0.6, fats: 0.0, carbohydrates: 72.9, calories: 282),
        ProductItem(name: "Варенье яблочное", category: categories[13], proteins: 0.4, fats: 0.0, carbohydrates: 68.7, calories: 260),
        ProductItem(name: "Вафли", category: categories[13], proteins: 3.2, fats: 2.8, carbohydrates: 52.0, calories: 342),
        ProductItem(name: "Галеты", category: categories[13], proteins: 11.0, fats: 1.5, carbohydrates: 75.0, calories: 360),
        ProductItem(name: "Зефир", category: categories[13], proteins: 0.7, fats: 0.1, carbohydrates: 78.3, calories: 299),
        ProductItem(name: "Зефир в шоколаде", category: categories[13], proteins: 2.0, fats: 10.0, carbohydrates: 70.0, calories: 365),
        ProductItem(name: "Какао-порошок", category: categories[13], proteins: 24.3, fats: 15.0, carbohydrates: 10.2, calories: 289),
        ProductItem(name: "Карамель", category: categories[13], proteins: 0.0, fats: 1.0, carbohydrates: 91.2, calories: 371),
        ProductItem(name: "Кекс с изюмом", category: categories[13], proteins: 6.4, fats: 17.6, carbohydrates: 53.6, calories: 384),
        ProductItem(name: "Козинак из семян подсолнечника", category: categories[13], proteins: 14.8, fats: 42.6, carbohydrates: 34.5, calories: 576),
        ProductItem(name: "Крахмал картофельный", category: categories[13], proteins: 0.1, fats: 0.0, carbohydrates: 79.6, calories: 299),
        ProductItem(name: "Круассаны", category: categories[13], proteins: 5.5, fats: 19.7, carbohydrates: 42.0, calories: 380),
        ProductItem(name: "Мармелад", category: categories[13], proteins: 0.0, fats: 0.1, carbohydrates: 77.7, calories: 296),
        ProductItem(name: "Мед натуральный", category: categories[13], proteins: 0.8, fats: 0.0, carbohydrates: 80.3, calories: 308),
        ProductItem(name: "Молоко сгущенное с сахаром 8,5%, Беларусь", category: categories[13], proteins: 7.2, fats: 8.5, carbohydrates: 56.0, calories: 329),
        ProductItem(name: "Мороженое молочное", category: categories[13], proteins: 3.2, fats: 3.5, carbohydrates: 21.3, calories: 126),
        ProductItem(name: "Мороженое пломбир", category: categories[13], proteins: 3.2, fats: 15.0, carbohydrates: 20.8, calories: 227),
        ProductItem(name: "Нуга", category: categories[13], proteins: 6.0, fats: 11.0, carbohydrates: 60.0, calories: 405),
        ProductItem(name: "Пастила", category: categories[13], proteins: 0.5, fats: 0.0, carbohydrates: 80.4, calories: 305),
        ProductItem(name: "Печенье", category: categories[13], proteins: 7.4, fats: 5.2, carbohydrates: 75.0, calories: 376),
        ProductItem(name: "Печенье овсяное", category: categories[13], proteins: 6.5, fats: 14.4, carbohydrates: 71.8, calories: 437),
        ProductItem(name: "Пирожные", category: categories[13], proteins: 1.0, fats: 9.2, carbohydrates: 42.0, calories: 370),
        ProductItem(name: "Повидло", category: categories[13], proteins: 0.1, fats: 0.1, carbohydrates: 57.0, calories: 215),
        ProductItem(name: "Пряники Тульские", category: categories[13], proteins: 5.5, fats: 6.5, carbohydrates: 68.0, calories: 360),
        ProductItem(name: "Рахат-лукум", category: categories[13], proteins: 0.0, fats: 0.7, carbohydrates: 79.0, calories: 310),
        ProductItem(name: "Торт медовый", category: categories[13], proteins: 5.4, fats: 26.0, carbohydrates: 42.0, calories: 430),
        ProductItem(name: "Торт Наполеон", category: categories[13], proteins: 5.9, fats: 33.0, carbohydrates: 23.0, calories: 410),
        ProductItem(name: "Торт Полет", category: categories[13], proteins: 5.7, fats: 24.8, carbohydrates: 55.4, calories: 456),
        ProductItem(name: "Торт Прага", category: categories[13], proteins: 4.6, fats: 24.0, carbohydrates: 42.0, calories: 410),
        ProductItem(name: "Торт Сказка", category: categories[13], proteins: 4.3, fats: 17.1, carbohydrates: 46.9, calories: 351),
        ProductItem(name: "Торт сметанно-ореховый", category: categories[13], proteins: 2.9, fats: 13.5, carbohydrates: 35.3, calories: 275),
        ProductItem(name: "Халва подсолнечная", category: categories[13], proteins: 11.6, fats: 29.7, carbohydrates: 54.0, calories: 516),
        ProductItem(name: "Чак-чак", category: categories[13], proteins: 8.6, fats: 1.9, carbohydrates: 77.9, calories: 363),
        ProductItem(name: "Шоколадный батончик Сникерс", category: categories[13], proteins: 9.3, fats: 27.9, carbohydrates: 54.6, calories: 507),
        ProductItem(name: "Шоколад горький", category: categories[13], proteins: 8.0, fats: 36.0, carbohydrates: 46.8, calories: 540),
        ProductItem(name: "Шоколад молочный", category: categories[13], proteins: 6.9, fats: 35.7, carbohydrates: 54.4, calories: 550)
    ],
    categories[14]: [
        ProductItem(name: "Абрикосовый сок", category: categories[14], proteins: 0.5, fats: 0.0, carbohydrates: 9.0, calories: 38),
        ProductItem(name: "Ананасовый сок", category: categories[14], proteins: 0.3, fats: 0.1, carbohydrates: 11.4, calories: 48),
        ProductItem(name: "Апельсиновый сок", category: categories[14], proteins: 0.7, fats: 0.1, carbohydrates: 8.1, calories: 36),
        ProductItem(name: "Березовый сок", category: categories[14], proteins: 0.1, fats: 0.0, carbohydrates: 5.8, calories: 24),
        ProductItem(name: "Виноградный сок", category: categories[14], proteins: 0.3, fats: 0.0, carbohydrates: 14.0, calories: 54),
        ProductItem(name: "Гранатовый сок", category: categories[14], proteins: 0.3, fats: 0.1, carbohydrates: 14.2, calories: 56),
        ProductItem(name: "Грейпфрутовый сок", category: categories[14], proteins: 0.3, fats: 0.1, carbohydrates: 6.5, calories: 29),
        ProductItem(name: "Грушевый сок", category: categories[14], proteins: 0.4, fats: 0.0, carbohydrates: 11.0, calories: 45),
        ProductItem(name: "Лаймовый сок, свежевыжатый", category: categories[14], proteins: 0.4, fats: 0.1, carbohydrates: 8.0, calories: 25),
        ProductItem(name: "Лимонный сок, свежевыжатый", category: categories[14], proteins: 0.35, fats: 0.24, carbohydrates: 6.6, calories: 22),
        ProductItem(name: "Манго сок", category: categories[14], proteins: 0.0, fats: 0.0, carbohydrates: 13.5, calories: 54),
        ProductItem(name: "Мандариновый сок", category: categories[14], proteins: 0.8, fats: 0.0, carbohydrates: 8.1, calories: 35),
        ProductItem(name: "Морковный сок", category: categories[14], proteins: 1.1, fats: 0.1, carbohydrates: 6.4, calories: 33),
        ProductItem(name: "Персиковый сок", category: categories[14], proteins: 0.3, fats: 0.0, carbohydrates: 9.5, calories: 39),
        ProductItem(name: "Томатный сок", category: categories[14], proteins: 1.0, fats: 0.1, carbohydrates: 2.9, calories: 18),
        ProductItem(name: "Тыквенный сок", category: categories[14], proteins: 0.0, fats: 0.0, carbohydrates: 9.0, calories: 38),
        ProductItem(name: "Яблочный сок", category: categories[14], proteins: 0.4, fats: 0.1, carbohydrates: 9.8, calories: 42),
        ProductItem(name: "7up", category: categories[14], proteins: 0.0, fats: 0.0, carbohydrates: 8.7, calories: 38),
        ProductItem(name: "Квас \"Очаковский\"", category: categories[14], proteins: 0.0, fats: 0.0, carbohydrates: 5.5, calories: 30),
        ProductItem(name: "Квас хлебный", category: categories[14], proteins: 0.2, fats: 0.0, carbohydrates: 5.2, calories: 27),
        ProductItem(name: "Кока-кола", category: categories[14], proteins: 0.0, fats: 0.0, carbohydrates: 10.4, calories: 42),
        ProductItem(name: "Кофе черный зерновой без сахара", category: categories[14], proteins: 0.2, fats: 0.5, carbohydrates: 0.3, calories: 7),
        ProductItem(name: "Кофе с молоком и сахаром", category: categories[14], proteins: 0.7, fats: 1.0, carbohydrates: 11.2, calories: 58),
        ProductItem(name: "Лимонад", category: categories[14], proteins: 0.0, fats: 0.0, carbohydrates: 6.4, calories: 26),
        ProductItem(name: "Пепси", category: categories[14], proteins: 0.0, fats: 0.0, carbohydrates: 8.7, calories: 38),
        ProductItem(name: "Пиво безалкогольное", category: categories[14], proteins: 0.0, fats: 0.0, carbohydrates: 4.1, calories: 22),
        ProductItem(name: "Тоник", category: categories[14], proteins: 0.0, fats: 0.0, carbohydrates: 8.3, calories: 34),
        ProductItem(name: "Фанта", category: categories[14], proteins: 0.0, fats: 0.0, carbohydrates: 11.7, calories: 48),
        ProductItem(name: "Цикорий растворимый", category: categories[14], proteins: 0.1, fats: 0.0, carbohydrates: 2.8, calories: 11),
        ProductItem(name: "Чай зеленый", category: categories[14], proteins: 0.0, fats: 0.0, carbohydrates: 0.0, calories: 0),
        ProductItem(name: "Чай черный без сахара", category: categories[14], proteins: 0.1, fats: 0.0, carbohydrates: 0.0, calories: 0),
        ProductItem(name: "Чай черный с сахаром", category: categories[14], proteins: 0.1, fats: 0.0, carbohydrates: 7.0, calories: 28),
        ProductItem(name: "Чай черный с молоком и сахаром", category: categories[14], proteins: 0.7, fats: 0.8, carbohydrates: 8.2, calories: 43)
    ],
    categories[15]: [
        ProductItem(name: "Вермут Cinzano, Martini", category: categories[15], proteins: 0, fats: 0, carbohydrates: 14.5, calories: 138),
        ProductItem(name: "Вина виноградные сухие белые и красные, в. т. ч. игристые", category: categories[15], proteins: 0.2, fats: 0, carbohydrates: 0.4, calories: 95),
        ProductItem(name: "Вина виноградные полусухие белые и красные, в. т. ч. игристые", category: categories[15], proteins: 0.3, fats: 0, carbohydrates: 2.5, calories: 78),
        ProductItem(name: "Вина виноградные полусладкие белые и красные, в. т. ч. игристые", category: categories[15], proteins: 0.2, fats: 0, carbohydrates: 5, calories: 88),
        ProductItem(name: "Вина виноградные сладкие белые и красные, в. т. ч. игристые", category: categories[15], proteins: 0.2, fats: 0, carbohydrates: 8, calories: 100),
        ProductItem(name: "Вина виноградные крепкие", category: categories[15], proteins: 0.4, fats: 0, carbohydrates: 12, calories: 163),
        ProductItem(name: "Вина виноградные ликерные", category: categories[15], proteins: 0.5, fats: 0, carbohydrates: 30, calories: 212),
        ProductItem(name: "Виски", category: categories[15], proteins: 0, fats: 0, carbohydrates: 0.4, calories: 235),
        ProductItem(name: "Водка", category: categories[15], proteins: 0, fats: 0, carbohydrates: 0.4, calories: 235),
        ProductItem(name: "Джин", category: categories[15], proteins: 0, fats: 0, carbohydrates: 0, calories: 230),
        ProductItem(name: "Джин-тоник", category: categories[15], proteins: 0, fats: 0, carbohydrates: 6.7, calories: 78),
        ProductItem(name: "Кагор", category: categories[15], proteins: 0, fats: 0, carbohydrates: 16, calories: 147),
        ProductItem(name: "Коньяк", category: categories[15], proteins: 0, fats: 0, carbohydrates: 0.1, calories: 239),
        ProductItem(name: "Ликер Amaretto", category: categories[15], proteins: 0, fats: 0, carbohydrates: 35, calories: 280),
        ProductItem(name: "Ликер Baileys", category: categories[15], proteins: 3, fats: 13, carbohydrates: 25, calories: 327),
        ProductItem(name: "Ликер \"Куантро\"", category: categories[15], proteins: 0, fats: 0, carbohydrates: 20, calories: 197),
        ProductItem(name: "Ликер \"Калуа\"", category: categories[15], proteins: 0.6, fats: 0.7, carbohydrates: 41.7, calories: 291),
        ProductItem(name: "Ликер \"Малибу\"", category: categories[15], proteins: 0, fats: 0, carbohydrates: 20, calories: 197),
        ProductItem(name: "Пиво светлое легкое", category: categories[15], proteins: 0.3, fats: 0, carbohydrates: 5.5, calories: 46),
        ProductItem(name: "Пиво темное легкое", category: categories[15], proteins: 0.3, fats: 0, carbohydrates: 5.7, calories: 48),
        ProductItem(name: "Портвейн", category: categories[15], proteins: 0.4, fats: 0, carbohydrates: 12, calories: 163),
        ProductItem(name: "Ром", category: categories[15], proteins: 0, fats: 0, carbohydrates: 0, calories: 220),
        ProductItem(name: "Саке", category: categories[15], proteins: 0.5, fats: 0, carbohydrates: 5, calories: 134),
        ProductItem(name: "Самогон", category: categories[15], proteins: 0.1, fats: 0.1, carbohydrates: 0.4, calories: 235),
        ProductItem(name: "Спирт этиловый 96%", category: categories[15], proteins: 4, fats: 0, carbohydrates: 3.8, calories: 710),
        ProductItem(name: "Текила", category: categories[15], proteins: 1.4, fats: 0.3, carbohydrates: 24, calories: 231),
        ProductItem(name: "Чача", category: categories[15], proteins: 0.1, fats: 0.1, carbohydrates: 0.5, calories: 225)
    ]
]
